local AddonName, SkillCapped = ...
local SC = SkillCapped

function SC:BetterBlizzPlatesDB()
    local scBetterBlizzPlatesDB = {
        ["npBgColorRGB"] = {
        1,
        1,
        1,
        1,
        },
        ["classIndicatorFriendlyScale"] = 1,
        ["otherNpdeBuffFilterCC"] = false,
        ["doNotHideFriendlyHealthbarInPve"] = false,
        ["hideNPCArenaOnly"] = false,
        ["nameplateKeyAuraScale"] = 1,
        ["NamePlateClassificationScale"] = "1.25",
        ["hideNPCHideSecondaryPets"] = true,
        ["nameplateSelfWidth"] = 154.0000152587891,
        ["auraColor"] = false,
        ["nameplatePlayerLargerScale"] = "1.8",
        ["friendlyNpBuffFilterLessMinite"] = false,
        ["otherNpdeBuffFilterWatchList"] = true,
        ["castBarInterruptHighlighterColorDontInterrupt"] = false,
        ["enableNameplateAuraCustomisation"] = true,
        ["customTextureFriendly"] = "Dragonflight (BBP)",
        ["classIndicatorXPos"] = 0,
        ["partyPointer"] = true,
        ["colorNPCName"] = false,
        ["questIndicatorTestMode"] = false,
        ["targetIndicatorYPos"] = 0,
        ["executeIndicatorScale"] = 1,
        ["healerIndicatorRedCrossEnemy"] = false,
        ["focusTargetIndicatorTexture"] = "Shattered DF (BBP)",
        ["friendlyClassColorName"] = false,
        ["castbarAlwaysOnTop"] = false,
        ["enemyNeutralHealthBarColorRGB"] = {
        1,
        1,
        0,
        },
        ["targetIndicatorScale"] = 1,
        ["changeNameplateBorderColor"] = false,
        ["disableCompactedAurasOnSelf"] = true,
        ["old_defaultLargeFontSize"] = 12,
        ["questIndicatorAnchor"] = "LEFT",
        ["otherNpBuffFilterPurgeable"] = false,
        ["otherNpdeBuffEnable"] = true,
        ["scStart"] = true,
        ["healthNumbersFriendly"] = false,
        ["combatIndicatorXPos"] = 0,
        ["friendlyNpdeBuffFilterWatchList"] = false,
        ["auraWhitelistColorsUpdated"] = true,
        ["nameplateAurasEnemyCenteredAnchor"] = false,
        ["classIndicatorScale"] = 1,
        ["hpHeightSelfMana"] = 10.8,
        ["showNpcTitle"] = false,
        ["partyPointerCCAuras"] = false,
        ["arenaIdAnchor"] = "TOP",
        ["importantCCDisarm"] = true,
        ["hideNameplateAuraTooltip"] = false,
        ["nameplateAurasPersonalYPos"] = 0,
        ["castBarNoninterruptibleColor"] = {
        0.4,
        0.4,
        0.4,
        },
        ["npAuraDiseaseRGB"] = {
        1,
        0.53,
        0.14,
        },
        ["healthNumbersUseMillions"] = false,
        ["focusTargetIndicatorTestMode"] = false,
        ["disableCVarForceOnLogin"] = false,
        ["old_defaultFontSize"] = 9,
        ["partyIndicatorModeThree"] = false,
        ["importantBuffsDefensives"] = true,
        ["partyPointerUpdated"] = true,
        ["absorbIndicator"] = false,
        ["arenaIndicatorModeOff"] = false,
        ["nameplateAuraRightToLeft"] = false,
        ["nameplateOverlapHScale"] = 0.5,
        ["nameplateShowEnemyGuardians"] = "1",
        ["castBarEmphasisSparkHeight"] = 35,
        ["nameplateAurasXPosXPos"] = 0,
        ["nameplateEnemyHeight"] = 64.125,
        ["targetIndicatorChangeTexture"] = false,
        ["fixedNameplateMotion"] = true,
        ["nameplateAurasYPos"] = -10,
        ["castBarEmphasisColor"] = false,
        ["petIndicatorHideSecondaryPets"] = true,
        ["nameplateShowFriendlyTotems"] = "0",
        ["enableMidnightNameplateTweaks"] = true,
        ["nameplateAurasNoNameYPos"] = 0,
        ["classIconReactionBorder"] = false,
        ["questIndicatorYPos"] = 0,
        ["bgIndicatorShowOrbs"] = true,
        ["enemyHealthBarColor"] = false,
        ["nameplateShowFriendlyMinions"] = "0",
        ["arenaIdXPos"] = 0,
        ["friendlyNameplatesOnlyInBgs"] = false,
        ["arenaIndicatorModeThree"] = false,
        ["castBarTextScale"] = 1,
        ["otherNpdeBuffFilterAll"] = false,
        ["colorNPC"] = false,
        ["classIndicatorAnchor"] = "TOP",
        ["druidAlwaysShowCombos"] = true,
        ["healthNumbersXPos"] = 0,
        ["arenaSpecAnchor"] = "TOP",
        ["questIndicator"] = true,
        ["nameplateFriendlyHeight"] = 64.125,
        ["partySpecScale"] = 1,
        ["nameplateMinScale"] = 0.9,
        ["otherNpBuffEmphasisedBorder"] = false,
        ["personalNpBuffFilterImportantBuffs"] = false,
        ["castBarIconScale"] = 1,
        ["nameplateShowFriendlyGuardians"] = "0",
        ["totemIndicatorHideNameAndShiftIconDown"] = false,
        ["nameplateAuraKeyAuraPositionFriendly"] = false,
        ["nameplateAuraRowAmount"] = 6,
        ["dpsOrHealNoAggroColorRGB"] = {
        0,
        1,
        0,
        1,
        },
        ["defaultLargeNamePlateFontFlags"] = "",
        ["castBarInterruptHighlighterEndTime"] = 0.6,
        ["nameplateAuraRelativeAnchor"] = "TOPLEFT",
        ["combatIndicatorEnemyOnly"] = false,
        ["partyPointerArenaOnly"] = true,
        ["ccIconAnchor"] = "RIGHT",
        ["healerIndicatorYPos"] = 0,
        ["npBorderNpcColorRGB"] = {
        0,
        0,
        0,
        1,
        },
        ["partyPointerHideAll"] = true,
        ["customHpFriendlyHeight"] = 0,
        ["hideEnemyNameText"] = false,
        ["darkModeNameplateColor"] = 0.2,
        ["npBorderEnemyColorRGB"] = {
        1,
        0,
        0,
        1,
        },
        ["hideRaidmarkIndicator"] = false,
        ["nameplateMaxAlpha"] = "1.0",
        ["changeHealthbarHeight"] = true,
        ["nameplateAuraEnlargedScale"] = 1,
        ["otherNpdeBuffFilterLessMinite"] = false,
        ["healthNumbersNotOnFullHp"] = false,
        ["enableCustomFontOutline"] = false,
        ["defaultOutlinedFontSize"] = 9,
        ["castBarInterruptHighlighterInterruptRGB"] = {
        0,
        1,
        0,
        },
        ["nameplateBorderSize"] = 1,
        ["partyPointerWidth"] = 36,
        ["nameplateResourceScale"] = 0.9,
        ["nameplateHorizontalScale"] = "1.4",
        ["healerIndicatorEnemyOnly"] = false,
        ["hideNpcMurlocScale"] = 1,
        ["old_defaultLargeNamePlateFontFlags"] = "",
        ["npBorderFriendFoeColor"] = false,
        ["healthNumbersFontOutline"] = "THICKOUTLINE",
        ["hideNameplateAuras"] = false,
        ["hidePersonalBarManaFrame"] = false,
        ["arenaIndicatorBg"] = false,
        ["arenaSpecScale"] = 1,
        ["focusTargetIndicatorChangeTexture"] = false,
        ["classIndicatorHideRaidMarker"] = true,
        ["partyPointerXPos"] = 0,
        ["classIconArenaOnly"] = false,
        ["classIconAlwaysShowTank"] = true,
        ["castBarEmphasisText"] = false,
        ["nameplateFriendlyWidth"] = 154.0000152587891,
        ["classicNameplates"] = false,
        ["skipGUI"] = true,
        ["castBarInterruptHighlighterStartPercentage"] = 15,
        ["petIndicatorScale"] = 1,
        ["nameplateOccludedAlphaMultScale"] = 0.8,
        ["otherNpBuffFilterImportantBuffs"] = false,
        ["fakeNameRaiseStrata"] = true,
        ["executeIndicatorThreshold"] = 40,
        ["totemIndicatorScaleUpImportant"] = false,
        ["defaultNamePlateOutlinedFont"] = "Fonts\\FRIZQT__.TTF",
        ["npBorderFriendlyColorRGB"] = {
        0,
        1,
        0,
        1,
        },
        ["interruptedByIndicator"] = true,
        ["tankFullAggroColorRGB"] = {
        0,
        1,
        0,
        1,
        },
        ["healerIndicatorScale"] = 1,
        ["castBarEmphasisOnlyInterruptable"] = false,
        ["totemListUpdateTWW6"] = true,
        ["nameplateShowFriendlyPlayerGuardians"] = "0",
        ["nameplateAuraWidthGapScale"] = 0,
        ["arenaSpecXPos"] = 0,
        ["friendlyNameplateNonstackable"] = true,
        ["nameplateShowEnemyMinus"] = "0",
        ["shortArenaSpecName"] = false,
        ["classColorPersonalNameplate"] = false,
        ["darkModeNameplateResource"] = false,
        ["hideLevelFrame"] = true,
        ["fadeOutNPC"] = true,
        ["otherNpdeBuffFilterOnlyMe"] = false,
        ["enemyColorThreatCombatOnlyPlayer"] = false,
        ["smallPetsWidth"] = 20,
        ["importantCCSilence"] = true,
        ["personalNpBuffFilterOnlyMe"] = false,
        ["separateAuraBuffRow"] = true,
        ["castBarEmphasisIcon"] = false,
        ["healerIndicatorAnchor"] = "TOPRIGHT",
        ["executeIndicatorShowDecimal"] = true,
        ["castBarEmphasisIconScale"] = 2,
        ["alwaysHideFriendlyCastbar"] = false,
        ["nameplateShowFriendlyNPCs"] = "0",
        ["healthNumbersShowDecimal"] = false,
        ["hideNPCsList"] = {
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Infernal",
        ["id"] = 89,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "",
        ["id"] = 24207,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Spirit Wolves Enha Shaman",
        ["id"] = 29264,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Treant",
        ["id"] = 54983,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Primal Fire Elemental",
        ["id"] = 61029,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Primal Earth Elemental",
        ["id"] = 61056,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Beast Hunter",
        ["id"] = 62005,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "mindbender",
        ["id"] = 62982,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Xuen",
        ["id"] = 63508,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Greater Storm Elemental",
        ["id"] = 77936,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Primal Storm Elemental",
        ["id"] = 77942,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Greater Fire Elemental",
        ["id"] = 95061,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Earth Elemental Shaman",
        ["id"] = 95072,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Greater Lightning Elemental",
        ["id"] = 97022,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Dreadstalker",
        ["id"] = 98035,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Darkglare",
        ["id"] = 103673,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Dire Basilisk Hunter",
        ["id"] = 105419,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Vilefiend",
        ["id"] = 135816,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Illidari Satyr",
        ["id"] = 136398,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Void Terror",
        ["id"] = 136403,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Darkhound",
        ["id"] = 136408,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Raise Abomination",
        ["id"] = 149555,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Magus Army of the Dead",
        ["id"] = 163366,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Thing From Beyond",
        ["id"] = 189988,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Void Lasher",
        ["id"] = 198757,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Water Elemental",
        ["id"] = 208441,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Overfiend",
        ["id"] = 217429,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Highlord Darion Mograine",
        ["id"] = 221632,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "High Inquisitor Whitemane",
        ["id"] = 221633,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Nazgrim",
        ["id"] = 221634,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "King Thoras Trollbane",
        ["id"] = 221635,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Voidwraith",
        ["id"] = 224466,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Doomguard",
        ["id"] = 225493,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Gloomhound",
        ["id"] = 226268,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Charhound",
        ["id"] = 226269,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Pit Lord",
        ["id"] = 228574,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Overlord",
        ["id"] = 228575,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Mother of Chaos",
        ["id"] = 228576,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Lesser Primal Storm Elemental",
        ["id"] = 229798,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Lesser Primal Fire Elemental",
        ["id"] = 229799,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Lesser Fire Elemental",
        ["id"] = 229800,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["important"] = false,
        ["pandemic"] = false,
        },
        ["comment"] = "Lesser Storm Elemental",
        ["id"] = 229801,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["pandemic"] = false,
        ["important"] = false,
        },
        ["comment"] = "Bear - Pack Leader",
        ["id"] = 234018,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "",
        },
        {
        ["flags"] = {
        ["murloc"] = false,
        },
        ["comment"] = "",
        ["id"] = 31216,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "Mirror Images (Mage)",
        },
        {
        ["flags"] = {
        ["murloc"] = false,
        },
        ["comment"] = "",
        ["id"] = 55659,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "Wild Imp (Warlock)",
        },
        {
        ["flags"] = {
        ["murloc"] = false,
        },
        ["comment"] = "",
        ["id"] = 143622,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "Wild Imp (Warlock)",
        },
        },
        ["partyIndicatorModeOne"] = false,
        ["adjustPersonalBarPosition"] = false,
        ["classIndicator"] = false,
        ["alwaysHideEnemyCastbar"] = false,
        ["castBarEmphasisHeightValue"] = 24,
        ["questIndicatorXPos"] = 0,
        ["otherNpdeBuffFilterBlacklist"] = true,
        ["castBarIconXPos"] = 0,
        ["nameplateOccludedAlphaMult"] = 0.8,
        ["fadeNPCPvPOnly"] = false,
        ["sortCompactedAurasFirst"] = false,
        ["totemIndicatorNpcList"] = {
        [105427] = {
        ["duration"] = 15,
        ["name"] = "Totem of Wrath",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0.27,
        0.59,
        },
        ["important"] = false,
        ["icon"] = 135829,
        ["size"] = 24,
        },
        [135002] = {
        ["duration"] = 15,
        ["name"] = "Tyrant",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0.69,
        0,
        },
        ["important"] = true,
        ["icon"] = 2065628,
        ["size"] = 30,
        },
        [105451] = {
        ["duration"] = 15,
        ["name"] = "Counterstrike Totem",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0.27,
        0.59,
        },
        ["important"] = true,
        ["icon"] = 511726,
        ["size"] = 30,
        },
        [59764] = {
        ["duration"] = 10,
        ["name"] = "Healing Tide Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0,
        1,
        0.39,
        },
        ["important"] = true,
        ["icon"] = 538569,
        ["size"] = 30,
        },
        [97285] = {
        ["duration"] = 18,
        ["name"] = "Wind Rush Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0.08,
        0.82,
        0.78,
        },
        ["important"] = false,
        ["icon"] = 538576,
        ["size"] = 24,
        },
        [179867] = {
        ["duration"] = 6,
        ["name"] = "Static Field Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0,
        1,
        0.78,
        },
        ["important"] = false,
        ["icon"] = 1020304,
        ["size"] = 24,
        },
        [225409] = {
        ["important"] = false,
        ["name"] = "Surging Totem",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0.36,
        0,
        },
        ["duration"] = 24,
        ["icon"] = 5927655,
        ["size"] = 24,
        },
        [104818] = {
        ["duration"] = 33,
        ["name"] = "Ancestral Protection Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0,
        1,
        0.78,
        },
        ["important"] = true,
        ["icon"] = 136080,
        ["size"] = 30,
        },
        [61245] = {
        ["duration"] = 2,
        ["name"] = "Capacitor Totem",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0.69,
        0,
        },
        ["important"] = true,
        ["icon"] = 136013,
        ["size"] = 30,
        },
        [3527] = {
        ["duration"] = 18,
        ["name"] = "Healing Stream Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0,
        1,
        0.78,
        },
        ["important"] = false,
        ["icon"] = 135127,
        ["size"] = 24,
        },
        [53006] = {
        ["duration"] = 6,
        ["name"] = "Spirit Link Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0,
        1,
        0.78,
        },
        ["important"] = true,
        ["icon"] = 237586,
        ["size"] = 30,
        },
        [97369] = {
        ["duration"] = 6,
        ["name"] = "Liquid Magma Totem",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0.69,
        0,
        },
        ["important"] = false,
        ["icon"] = 971079,
        ["size"] = 24,
        },
        [2630] = {
        ["duration"] = 30,
        ["name"] = "Earthbind Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0.78,
        0.51,
        0.39,
        },
        ["important"] = false,
        ["icon"] = 136102,
        ["size"] = 24,
        },
        [224466] = {
        ["important"] = false,
        ["name"] = "Voidwrath",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0.69,
        0,
        },
        ["duration"] = 15,
        ["icon"] = 615099,
        ["size"] = 24,
        },
        [107024] = {
        ["duration"] = 15,
        ["name"] = "Fel Lord",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0.69,
        0,
        },
        ["important"] = true,
        ["icon"] = 1113433,
        ["size"] = 30,
        },
        [185800] = {
        ["important"] = false,
        ["name"] = "Past Self",
        ["hideIcon"] = false,
        ["color"] = {
        0.36,
        0.56,
        0.52,
        },
        ["duration"] = 8,
        ["icon"] = 4622470,
        ["size"] = 24,
        },
        [78001] = {
        ["duration"] = 15,
        ["name"] = "Cloudburst Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0,
        1,
        0.39,
        },
        ["important"] = false,
        ["icon"] = 971076,
        ["size"] = 24,
        },
        [62982] = {
        ["duration"] = 15,
        ["name"] = "Mindbender",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0.69,
        0,
        },
        ["important"] = false,
        ["icon"] = 136214,
        ["size"] = 24,
        },
        [5923] = {
        ["duration"] = 9,
        ["name"] = "Poison Cleansing Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0.49,
        0.9,
        0.08,
        },
        ["important"] = false,
        ["icon"] = 136070,
        ["size"] = 24,
        },
        [225672] = {
        ["duration"] = 4,
        ["name"] = "Shadow",
        ["hideIcon"] = false,
        ["color"] = {
        0.49,
        0,
        1,
        },
        ["important"] = true,
        ["icon"] = 136184,
        ["size"] = 35,
        },
        [59712] = {
        ["important"] = true,
        ["name"] = "Stone Bulwark Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0.98,
        0.75,
        0.17,
        },
        ["duration"] = 30,
        ["icon"] = 538572,
        ["size"] = 30,
        },
        [101398] = {
        ["duration"] = 12,
        ["name"] = "Psyfiend",
        ["hideIcon"] = false,
        ["color"] = {
        0.49,
        0,
        1,
        },
        ["important"] = true,
        ["icon"] = 537021,
        ["size"] = 35,
        },
        [114565] = {
        ["duration"] = 10,
        ["name"] = "Guardian of the Forgotten Queen",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0,
        1,
        },
        ["important"] = true,
        ["icon"] = 135919,
        ["size"] = 30,
        },
        [5913] = {
        ["duration"] = 13,
        ["name"] = "Tremor Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0.49,
        0.9,
        0.08,
        },
        ["important"] = true,
        ["icon"] = 136108,
        ["size"] = 30,
        },
        [5925] = {
        ["duration"] = 3,
        ["name"] = "Grounding Totem",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0,
        1,
        },
        ["important"] = true,
        ["icon"] = 136039,
        ["size"] = 30,
        },
        [196111] = {
        ["duration"] = 10,
        ["name"] = "Pit Lord",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0.69,
        0,
        },
        ["important"] = false,
        ["icon"] = 236423,
        ["size"] = 24,
        },
        [194118] = {
        ["duration"] = 20,
        ["name"] = "Tranquil Air Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0,
        1,
        0.78,
        },
        ["important"] = false,
        ["icon"] = 538575,
        ["size"] = 24,
        },
        [65282] = {
        ["duration"] = 6,
        ["name"] = "Void Tendril",
        ["hideIcon"] = false,
        ["color"] = {
        0.33,
        0.35,
        1,
        },
        ["important"] = false,
        ["icon"] = 537022,
        ["size"] = 24,
        },
        [14465] = {
        ["name"] = "Alliance Battle Standard",
        ["hideIcon"] = false,
        ["color"] = {
        0,
        0.22,
        1,
        },
        ["important"] = true,
        ["icon"] = 132486,
        ["size"] = 24,
        },
        [89] = {
        ["duration"] = 30,
        ["name"] = "Infernal",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0.69,
        0,
        },
        ["important"] = false,
        ["icon"] = 136219,
        ["size"] = 24,
        },
        [194117] = {
        ["duration"] = 15,
        ["name"] = "Stoneskin Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0.78,
        0.49,
        0.35,
        },
        ["important"] = false,
        ["icon"] = 4667425,
        ["size"] = 24,
        },
        [14466] = {
        ["name"] = "Horde Battle Standard",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0,
        0,
        },
        ["important"] = true,
        ["icon"] = 132485,
        ["size"] = 24,
        },
        [19668] = {
        ["important"] = false,
        ["name"] = "Shadowfiend",
        ["hideIcon"] = false,
        ["color"] = {
        1,
        0.69,
        0,
        },
        ["duration"] = 15,
        ["icon"] = 136199,
        ["size"] = 24,
        },
        [60561] = {
        ["duration"] = 30,
        ["name"] = "Earthgrab Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0.75,
        0.31,
        0.1,
        },
        ["important"] = false,
        ["icon"] = 136100,
        ["size"] = 24,
        },
        [100943] = {
        ["duration"] = 18,
        ["name"] = "Earthen Wall Totem",
        ["hideIcon"] = false,
        ["color"] = {
        0.78,
        0.49,
        0.35,
        },
        ["important"] = true,
        ["icon"] = 136098,
        ["size"] = 24,
        },
        },
        ["classIconColorBorder"] = true,
        ["enemyNeutralColorNameRGB"] = {
        1,
        1,
        0,
        },
        ["targetIndicatorColorName"] = false,
        ["classIconHealthNumbers"] = false,
        ["partyPointerHealerOnly"] = false,
        ["nameplateAuraRowAbove"] = true,
        ["totemIndicatorWidthEnabled"] = false,
        ["nameplateEnemyWidth"] = 150,
        ["classIndicatorShowPet"] = true,
        ["nameplateAuraCompactedSquare"] = false,
        ["nameplateShowAll"] = "1",
        ["absorbIndicatorOnPlayersOnly"] = true,
        ["fadeAllButTarget"] = false,
        ["healthNumbersYPos"] = 0,
        ["raidmarkIndicatorXPos"] = 0,
        ["bgIndicator"] = false,
        ["targetNameplateAuraScaleEnabled"] = false,
        ["castBarDelayedInterruptColor"] = {
        1,
        0.4784314036369324,
        0.9568628072738647,
        },
        ["executeIndicatorYPos"] = 0,
        ["otherNpBuffFilterLessMinite"] = false,
        ["hideResourceOnFriend"] = true,
        ["skipAdjustingFixedFonts"] = false,
        ["friendlyNameplatesOnlyInWorld"] = false,
        ["friendlyNpBuffFilterWatchList"] = false,
        ["showCastbarIfTarget"] = false,
        ["partyPointerAlwaysShowPet"] = false,
        ["sortEnlargedAurasFirst"] = true,
        ["castBarIconPosReset"] = true,
        ["classIndicatorFrameStrataHigh"] = false,
        ["absorbIndicatorXPos"] = 0,
        ["partyIndicatorModeFive"] = false,
        ["showGuildNames"] = false,
        ["healerIndicatorEnemyXPos"] = 0,
        ["hpHeightFriendly"] = 10.8,
        ["targetIndicator"] = false,
        ["nameplateShowClassColor"] = "1",
        ["nameplateDefaultLargeFriendlyHeight"] = 64.125,
        ["npBorderTargetColor"] = false,
        ["npBorderClassColor"] = false,
        ["hideCastbarText"] = false,
        ["hpHeightEnemy"] = 10.8,
        ["arenaIndicatorModeTwo"] = false,
        ["castBarEmphasisHeight"] = false,
        ["otherNpBuffFilterAll"] = false,
        ["castBarIconYPos"] = 0,
        ["hideFriendlyNameText"] = true,
        ["nameplateResourceOnTarget"] = true,
        ["fakeNameAnchor"] = "BOTTOM",
        ["castBarShieldScale"] = 1,
        ["classIconBgOnly"] = false,
        ["classIconEnemyHealIcon"] = true,
        ["hideDefaultPersonalNameplateAuras"] = false,
        ["npcTitleColor"] = false,
        ["partyPointerTestMode"] = false,
        ["personalNpBuffFilterBlizzard"] = true,
        ["friendlyNpBuffFilterOnlyMe"] = false,
        ["personalNpBuffFilterLessMinite"] = false,
        ["npBorderNonTargetColorRGB"] = {
        0,
        0,
        0,
        1,
        },
        ["nameplateResourceYPos"] = 0,
        ["nameplateSelectedScale"] = 1.2,
        ["castBarBackgroundColor"] = {
        0.33,
        0.33,
        0.33,
        1,
        },
        ["friendlyNameplatesOnlyInRaids"] = false,
        ["nameplateAuraSelfScale"] = 1,
        ["friendlyHealthBarColorPlayer"] = false,
        ["castBarNoInterruptColor"] = {
        1,
        0,
        0.01568627543747425,
        },
        ["guildNameScale"] = 1,
        ["hidePersonalBarExtraFrame"] = false,
        ["friendlyHealthBarColorRGB"] = {
        0,
        1,
        0,
        },
        ["classIndicatorHealer"] = false,
        ["nameplateAuraRowFriendlyAmountScale"] = 6,
        ["hideNPCWhitelistOn"] = false,
        ["nameplateAuraTaller"] = false,
        ["classIndicatorOnlyFriends"] = false,
        ["petIndicatorYPos"] = 0,
        ["changeResourceStrata"] = false,
        ["showCircleOnArenaID"] = false,
        ["defaultLargeNamePlateFont"] = "Fonts\\FRIZQT__.TTF",
        ["skipBugWarning"] = true,
        ["nameplateVerticalPosition"] = 0,
        ["castBarHeightHeight"] = 15,
        ["arenaIdYPos"] = 0,
        ["partyPointerWidthScale"] = 36,
        ["classIndicatorHighlight"] = false,
        ["npcColorMelee"] = {
        1,
        0,
        0,
        1,
        },
        ["castBarHeight"] = 15,
        ["npBorderTargetColorRGB"] = {
        1,
        1,
        1,
        1,
        },
        ["classIndicatorSpecIcon"] = false,
        ["nameplateShowFriendlyPlayerMinions"] = "0",
        ["castBarEmphasisSpark"] = false,
        ["npcColorMinus"] = {
        0.63,
        0.28,
        0.17,
        1,
        },
        ["totemIndicatorColorName"] = true,
        ["nameplateAuraRectangleSize"] = false,
        ["nameplateHorizontalPosition"] = 0,
        ["npcColorRareElite"] = {
        0.49,
        1,
        0.74,
        1,
        },
        ["customFontSizeEnabled"] = false,
        ["partyPointerHideRaidmarker"] = true,
        ["alwaysShowPurgeTexture"] = true,
        ["nameplateExtraClickWidth"] = 0,
        ["friendlyNpBuffFilterBlacklist"] = true,
        ["ccIconScale"] = 2,
        ["castBarInterruptHighlighter"] = false,
        ["nameplateAurasXPos"] = 0,
        ["cleanedScaleScale"] = true,
        ["executeIndicatorAnchor"] = "LEFT",
        ["totemIndicatorHideHealthBar"] = false,
        ["fakeNameScaleWithParent"] = false,
        ["enableNpVerticalPos"] = false,
        ["targetIndicatorColorNameplate"] = false,
        ["friendlyNameplatesOnlyInEpicBgs"] = false,
        ["updates"] = "v2.2.6f",
        ["fixedFriendlyHealthbarHide"] = true,
        ["castBarIconAnchor"] = "LEFT",
        ["healthNumbersTestMode"] = false,
        ["personalNpdeBuffEnable"] = false,
        ["npBorderFocusColorRGB"] = {
        0,
        0,
        0,
        1,
        },
        ["partyPointerShowOthersPets"] = false,
        ["hideNpcMurlocYPos"] = 0,
        ["nameplateAurasPersonalCenteredAnchor"] = false,
        ["nameplateDefaultEnemyHeight"] = 45,
        ["useCustomCastbarTexture"] = false,
        ["totemIndicatorUseNicknames"] = false,
        ["otherNpBuffFilterWatchList"] = true,
        ["nameplateAuraPixelBorder"] = false,
        ["castBarEmphasisTextScale"] = 2,
        ["nameplateShowEnemyTotems"] = "1",
        ["castbarEventsOn"] = false,
        ["nameplateShadowRGB"] = {
        0,
        0,
        0,
        1,
        },
        ["nameplateTargetBorderSize"] = 3,
        ["showNameplateCastbarTimer"] = false,
        ["levelFrameFontSize"] = 12,
        ["partyPointerShowPet"] = true,
        ["petIndicatorShowMurloc"] = true,
        ["partyIndicatorModeOff"] = false,
        ["focusTargetIndicatorColorNameplateRGB"] = {
        1,
        1,
        1,
        },
        ["otherNpdeBuffPandemicGlow"] = false,
        ["useCustomTextureForSelf"] = false,
        ["nameplateAurasPersonalXPos"] = 0,
        ["useCustomTextureForFriendly"] = true,
        ["castBarShieldAnchor"] = "LEFT",
        ["showNameplateShadowOnlyTarget"] = false,
        ["anonMode"] = false,
        ["enableNpNonTargetAlpha"] = false,
        ["targetNameplateAuraScale"] = 1,
        ["healerIndicatorEnemyAnchor"] = "TOPRIGHT",
        ["partyPointerHighlightRGB"] = {
        1,
        0.71,
        0,
        },
        ["enemyColorThreatCombatOnly"] = false,
        ["classIndicatorBackgroundRGB"] = {
        0,
        0,
        0,
        1,
        },
        ["nameplateMinAlpha"] = 0.90135484,
        ["showNameplateShadow"] = false,
        ["targetIndicatorHideIcon"] = false,
        ["showDefaultCooldownNumbersOnNpAuras"] = false,
        ["focusTargetIndicatorColorNameplate"] = false,
        ["reopenOptions"] = false,
        ["hasSaved"] = true,
        ["friendlyNpdeBuffFilterBlacklist"] = true,
        ["classIndicatorOnlyHealer"] = false,
        ["otherNpdeBuffFilterBlizzard"] = false,
        ["tankOffTankAggroColorRGB"] = {
        0,
        0.95,
        1,
        1,
        },
        ["friendIndicator"] = false,
        ["partyPointerHighlightScale"] = 1,
        ["defaultLargeFontSize"] = 12,
        ["nameplateKeyAurasHorizontalGap"] = 5,
        ["partyPointerTexture"] = 1,
        ["castBarDragonflightShield"] = true,
        ["useFakeNameAnchorBottom"] = false,
        ["classIndicatorPinMode"] = false,
        ["castBarIconPixelBorder"] = false,
        ["old_defaultLargeNamePlateFont"] = "Fonts\\FRIZQT__.TTF",
        ["enemyColorName"] = false,
        ["keyAurasImportantBuffsEnabled"] = true,
        ["enableNpNonFocusAlpha"] = false,
        ["importantCCRootGlowRGB"] = {
        ["a"] = 1,
        ["r"] = 1,
        ["g"] = 0.874,
        ["b"] = 0,
        },
        ["partyPointerUpdated2"] = true,
        ["classIndicatorEnemy"] = true,
        ["nameplateResourceXPosXPos"] = 0,
        ["nameplateMotion"] = "1",
        ["nameplateShadowHighlightRGB"] = {
        1,
        1,
        1,
        1,
        },
        ["totemListUpdateTWW4"] = true,
        ["castBarPixelBorder"] = false,
        ["nameplateResourceUnderCastbar"] = true,
        ["nameplateResourceDoNotRaiseAuras"] = false,
        ["totemListUpdateTWW1"] = true,
        ["classIndicatorFriendlyXPos"] = 0,
        ["hideCastbarBorderShield"] = false,
        ["nameplateKeyAurasAnchor"] = "RIGHT",
        ["arenaIndicatorModeFour"] = false,
        ["absorbIndicatorScale"] = 1,
        ["raidmarkIndicator"] = false,
        ["personalNpTRP3Color"] = false,
        ["nameplateAuraSquare"] = false,
        ["totemIndicatorEnemyOnly"] = true,
        ["friendlyNpdeBuffFilterCC"] = true,
        ["druidOverstacks"] = false,
        ["auraColorPvEOnly"] = false,
        ["enemyHealthBarColorNpcOnly"] = false,
        ["nameplateShowFriendlyPets"] = "0",
        ["nameplateAuraKeyAuraPositionEnabled"] = false,
        ["totemListUpdateTWW3"] = true,
        ["castBarEmphasisHealthbarColor"] = false,
        ["personalBarPosition"] = 0.5,
        ["healthNumbersOnlyInCombat"] = false,
        ["totemListUpdateTWW2"] = true,
        ["importantBuffsMobilityGlowRGB"] = {
        ["a"] = 1,
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 1,
        },
        ["onlyShowHighlightedNpShadow"] = false,
        ["customTextureSelfMana"] = "Solid",
        ["customFontSize"] = 12,
        ["hideEliteDragon"] = false,
        ["classIndicatorHideName"] = false,
        ["nameplateAurasYPosYPos"] = -10,
        ["keepNpShadowTargetHighlighted"] = false,
        ["personalBarTweaks"] = false,
        ["skipCVarsPlater"] = true,
        ["nameplateMinAlphaScale"] = 1,
        ["nameplateStyle"] = "0",
        ["importantBuffsOffensives"] = true,
        ["friendlyNpBuffPurgeGlow"] = false,
        ["useCustomTextureForEnemy"] = true,
        ["threatColorAlwaysOn"] = false,
        ["healthNumbersCurrentFull"] = false,
        ["healthNumbersScale"] = 1,
        ["castBarShieldYPos"] = 0,
        ["totemIndicatorHideAuras"] = true,
        ["showCastBarIconWhenNoninterruptible"] = true,
        ["nameplateDefaultLargeEnemyHeight"] = 64.125,
        ["healthNumbersJustify"] = "CENTER",
        ["nameplateResourceYPosYPos"] = 0,
        ["useCustomTextureForExtraBars"] = false,
        ["raidmarkIndicatorRaiseStrata"] = false,
        ["otherNpBuffEnable"] = true,
        ["hideCastbarWhitelistOn"] = false,
        ["importantBuffsMobilityGlow"] = true,
        ["personalNpdeBuffFilterLessMinite"] = false,
        ["tankNoAggroColorRGB"] = {
        1,
        0,
        0,
        1,
        },
        ["enemyColorThreat"] = false,
        ["hideTempHpLoss"] = false,
        ["customFontOutline"] = "THINOUTLINE",
        ["hideNpAuraSwipe"] = false,
        ["classIndicatorHighlightColor"] = false,
        ["classIndicatorBackground"] = false,
        ["executeIndicatorUseTexture"] = false,
        ["enemyColorThreatHideSolo"] = false,
        ["useCustomTextureForBars"] = false,
        ["hideNameDuringCast"] = false,
        ["smallPetsInPvP"] = false,
        ["showNameplateTargetText"] = false,
        ["nameplateCastbarTestMode"] = false,
        ["dbCleanMidnight"] = true,
        ["nameplateGeneralHpHeight"] = 16.3,
        ["friendlyNpBuffEmphasisedBorder"] = false,
        ["blizzardDefaultFilterOnlyMine"] = false,
        ["partyIDScale"] = 1,
        ["classIconSquareBorder"] = false,
        ["nameplateOverlapV"] = 1.1,
        ["nameplateMinAlphaDistance"] = -158489.31924611,
        ["buffIconXPos"] = 0,
        ["petIndicator"] = true,
        ["enemyNameplateHealthbarHeight"] = 4,
        ["nameplateAuraBuffScale"] = 1,
        ["customFont"] = "Prototype",
        ["nameplateSelfHeight"] = 45.00000381469727,
        ["nameplateCenterAllRows"] = false,
        ["fakeNameAnchorRelative"] = "TOP",
        ["totemIndicatorXPos"] = 0,
        ["importantCCFullGlowRGB"] = {
        ["a"] = 1,
        ["r"] = 1,
        ["g"] = 0.874,
        ["b"] = 0,
        },
        ["nameplateSelfAlpha"] = "1",
        ["bgIndicatorYPos"] = 0,
        ["personalNpBuffEnable"] = true,
        ["disableEnlargedAurasOnSelf"] = true,
        ["castBarEmphasisSelfColor"] = false,
        ["hideNPCPetsOnly"] = false,
        ["nameplateAurasCenteredAnchor"] = false,
        ["old_defaultNamePlateFontFlags"] = "",
        ["executeIndicatorInRangeColor"] = false,
        ["nameplateAuraCompactedScale"] = 1,
        ["totemIndicatorAnchor"] = "TOP",
        ["partyPointerHealerReplace"] = true,
        ["totemIndicatorYPos"] = 0,
        ["friendlyHideHealthBar"] = false,
        ["hideCastbarIcon"] = false,
        ["tankLosingAggroColorRGB"] = {
        1,
        0.47,
        0,
        1,
        },
        ["hideNPCHideOthersPets"] = true,
        ["bgIndicatorScale"] = 1,
        ["defaultNamePlateFontFlags"] = "SLUG",
        ["fadeOutNPCsAlpha"] = 0.2,
        ["nameplateExtraClickHeight"] = 0,
        ["nameplateAuraBuffSelfScale"] = 1,
        ["castBarChanneledColor"] = {
        0.4862745404243469,
        1,
        0.294117659330368,
        },
        ["otherNpBuffFilterBlacklist"] = true,
        ["combatIndicator"] = false,
        ["nameplateShowFriendlyPlayerPets"] = "0",
        ["NamePlateVerticalScale"] = 2.7,
        ["npAuraOtherRGB"] = {
        0,
        0,
        0,
        },
        ["overShields"] = false,
        ["totemIndicatorNoAnimation"] = false,
        ["nameplateResourceXPos"] = 0,
        ["healthNumbersSwapped"] = false,
        ["classIndicatorFriendlyYPos"] = 0,
        ["friendlyColorName"] = false,
        ["hideNpcCastbar"] = false,
        ["classIndicatorHideFriendlyHealthbar"] = false,
        ["healthNumbersPercentage"] = false,
        ["personalNpdeBuffFilterCC"] = false,
        ["healthNumbersHideSelf"] = false,
        ["changeNameplateBorderSize"] = false,
        ["customTextureSelf"] = "Solid",
        ["bgIndicatorXPos"] = 0,
        ["defaultFontSize"] = 9,
        ["combatIndicatorAnchor"] = "CENTER",
        ["nameplateAuraHeightGap"] = 4,
        ["absorbIndicatorYPos"] = 0,
        ["hideNPC"] = true,
        ["sortDurationAuras"] = false,
        ["enableCastbarCustomization"] = true,
        ["partyPointerYPos"] = -40,
        ["questIndicatorScale"] = 1,
        ["raidmarkerPvPOnly"] = false,
        ["nameplateAuraPlayersOnly"] = false,
        ["enableNpNonTargetAlphaFullAlphaCasting"] = false,
        ["npcColorCaster"] = {
        0,
        0.749,
        1,
        1,
        },
        ["executeIndicatorFriendly"] = false,
        ["absorbIndicatorAnchor"] = "LEFT",
        ["defaultNamePlateFont"] = "Fonts\\FRIZQT__.TTF",
        ["friendlyNpBuffFilterAll"] = false,
        ["showInterruptsOnNameplateAuras"] = true,
        ["combatIndicatorPlayersOnly"] = true,
        ["highlightNpShadowOnMouseover"] = false,
        ["dpsOrHealFullAggroColorRGB"] = {
        1,
        0,
        0,
        1,
        },
        ["customTexture"] = "Dragonflight (BBP)",
        ["totemIndicatorDefaultCooldownTextSize"] = 0.85,
        ["hideResourceFrame"] = false,
        ["arenaModeSettingKey"] = "1: Replace name with Arena ID",
        ["totemIndicatorScale"] = 1,
        ["petIndicatorTestMode"] = false,
        ["targetIndicatorTexture"] = "Checkered (BBP)",
        ["nameplateOverlapH"] = 0.5,
        ["combatIndicatorArenaOnly"] = false,
        ["bgIndicatorEnemyOnly"] = true,
        ["classIndicatorOnlyParty"] = false,
        ["focusTargetIndicatorYPos"] = 0,
        ["personalNpdeBuffFilterBlacklist"] = true,
        ["executeIndicatorInRangeColorRGB"] = {
        0,
        1,
        0.8,
        1,
        },
        ["healerIndicatorEnemyScale"] = 1,
        ["classIndicatorUpdated2"] = true,
        ["useCustomCastbarBGTexture"] = false,
        ["nameplateDefaultEnemyWidth"] = 110,
        ["friendlyNameScale"] = 1,
        ["focusTargetIndicatorScale"] = 1,
        ["fakeNameYPos"] = 0,
        ["castBarFullTextWidth"] = false,
        ["bitfields"] = {
        ["nameplateFriendlyPlayerAuraDisplay"] = {
        ["1"] = false,
        ["3"] = false,
        ["2"] = false,
        },
        ["nameplateSimplifiedTypes"] = {
        ["1"] = false,
        ["4"] = false,
        ["3"] = false,
        ["2"] = false,
        },
        ["nameplateStackingTypes"] = {
        ["1"] = true,
        ["2"] = false,
        },
        ["nameplateEnemyNpcAuraDisplay"] = {
        ["1"] = false,
        ["3"] = false,
        ["2"] = true,
        },
        ["nameplateCastBarDisplay"] = {
        ["1"] = true,
        ["3"] = false,
        ["2"] = true,
        ["5"] = true,
        ["4"] = true,
        },
        ["nameplateThreatDisplay"] = {
        ["1"] = false,
        ["3"] = false,
        ["2"] = false,
        },
        ["nameplateInfoDisplay"] = {
        ["1"] = false,
        ["3"] = true,
        ["2"] = false,
        },
        ["nameplateEnemyPlayerAuraDisplay"] = {
        ["1"] = false,
        ["3"] = false,
        ["2"] = true,
        },
        },
        ["personalNpdeBuffFilterAll"] = false,
        ["nameplateAuraPlayersOnlyShowTarget"] = false,
        ["nameplateShowFriendlyClassColor"] = "0",
        ["totemIndicatorTestMode"] = false,
        ["partyPointerHighlight"] = false,
        ["healerIndicatorArenaOnly"] = false,
        ["importantBuffsDefensivesGlow"] = true,
        ["importantBuffsOffensivesGlowRGB"] = {
        ["a"] = 1,
        ["r"] = 1,
        ["g"] = 0.5,
        ["b"] = 0,
        },
        ["nameplateAuraScale"] = 1.5,
        ["npBorderNeutralColorRGB"] = {
        1,
        1,
        0,
        1,
        },
        ["wasOnLoadingScreen"] = true,
        ["targetIndicatorXPos"] = 0,
        ["nameplateResourcePositionFix"] = true,
        ["enemyHealthBarColorRGB"] = {
        1,
        0,
        0,
        },
        ["fakeNameXPos"] = 0,
        ["keyAurasImportantGlowOn"] = true,
        ["castBarInterruptHighlighterEndPercentage"] = 80,
        ["focusTargetIndicatorColorName"] = false,
        ["focusTargetIndicatorXPos"] = 0,
        ["nameplateKeyAurasXPos"] = 0,
        ["combatIndicatorScale"] = 1,
        ["personalNpBuffFilterAll"] = false,
        ["castbarQuickHide"] = true,
        ["friendlyHideHealthBarNpc"] = false,
        ["castBarInterruptHighlighterStartTime"] = 0.8,
        ["hideTargetHighlight"] = false,
        ["nameplateAuraEnlargedSquare"] = true,
        ["npcTitleScale"] = 1,
        ["hideNPCSecondaryShowMurloc"] = true,
        ["npAuraPoisonRGB"] = {
        0,
        0.52,
        0.031,
        },
        ["classIconHealerIconType"] = 2,
        ["executeIndicatorAlwaysOn"] = false,
        ["raidmarkIndicatorScale"] = 1,
        ["partyIndicatorModeFour"] = false,
        ["friendlyNpdeBuffFilterAll"] = false,
        ["nameplateShowFriendlyPlayerTotems"] = "0",
        ["friendlyNpdeBuffEnable"] = true,
        ["arenaIndicatorModeFive"] = false,
        ["scTotem"] = true,
        ["partyPointerOnlyParty"] = false,
        ["customHpHeight"] = 0,
        ["enableCastbarEmphasis"] = false,
        ["healerIndicator"] = true,
        ["partyPointerHealer"] = true,
        ["useFakeName"] = true,
        ["executeIndicatorXPos"] = 0,
        ["castBarInterruptHighlighterDontInterruptRGB"] = {
        0,
        0,
        0,
        },
        ["setCVarAcrossAllCharacters"] = true,
        ["importantCCRoot"] = true,
        ["onlyShowInterruptableCasts"] = false,
        ["friendlyNameplateClickthrough"] = false,
        ["totemIndicatorColorHealthBar"] = true,
        ["healthNumbersTargetOnly"] = false,
        ["healthNumbersPercentSymbol"] = false,
        ["healthNumbersAnchor"] = "CENTER",
        ["npcColorBoss"] = {
        0.76,
        0.6,
        0.42,
        1,
        },
        ["arenaIndicatorTestMode"] = false,
        ["personalNpdeBuffFilterWatchList"] = true,
        ["targetIndicatorAnchor"] = "TOP",
        ["healthNumbersClassColor"] = false,
        ["nameplateDefaultLargeFriendlyWidth"] = 154,
        ["importantBuffsMobility"] = true,
        ["nameplateAuraRowAmountScale"] = 6,
        ["fakeNameFriendlyYPos"] = 0,
        ["defaultNamePlateOutlinedFontFlags"] = "OUTLINE, SLUG",
        ["healerIndicatorXPos"] = 0,
        ["npAuraMagicRGB"] = {
        0.13,
        0.44,
        1,
        },
        ["hideNPCAllNeutral"] = false,
        ["classIndicatorAlpha"] = 1,
        ["castBarShieldXPos"] = 0,
        ["largeNameplates"] = false,
        ["absorbIndicatorEnemyOnly"] = false,
        ["otherNpBuffBlueBorder"] = false,
        ["executeIndicatorPercentSymbol"] = false,
        ["nameplateShowEnemyPets"] = "1",
        ["healthNumbers"] = false,
        ["showLastNameNpc"] = false,
        ["onlyPandemicAuraMine"] = true,
        ["nameplateShowEnemyMinions"] = "0",
        ["guildNameColorRGB"] = {
        0,
        1,
        0,
        },
        ["raidmarkIndicatorFullAlpha"] = false,
        ["removeRealmNames"] = true,
        ["petIndicatorAnchor"] = "CENTER",
        ["enlargeAllImportantBuffs"] = true,
        ["importantCCFull"] = true,
        ["nameplateAuraWidthGap"] = 0,
        ["classIconSquareBorderFriendly"] = false,
        ["importantBuffsDefensivesGlowRGB"] = {
        ["a"] = 1,
        ["r"] = 1,
        ["g"] = 0.662,
        ["b"] = 0.945,
        },
        ["useCustomFont"] = true,
        ["testAllEnabledFeatures"] = false,
        ["partyPointerTargetIndicator"] = true,
        ["combatIndicatorYPos"] = 0,
        ["partyPointerHealerScale"] = 1.25,
        ["enemyNameScale"] = 1,
        ["classIndicatorYPos"] = 0,
        ["guildNameColor"] = false,
        ["friendlyNpBuffBlueBorder"] = false,
        ["changeNpHpBgColorSolid"] = false,
        ["importantBuffsOffensivesGlow"] = true,
        ["raidmarkIndicatorAnchor"] = "TOP",
        ["classIndicatorFriendly"] = true,
        ["nameplateAuraCountScale"] = 1,
        ["combatIndicatorSap"] = false,
        ["executeIndicatorNotOnFullHp"] = false,
        ["focusTargetIndicatorAnchor"] = "TOPRIGHT",
        ["nameplateDebuffPadding"] = 15,
        ["executeIndicatorTargetOnly"] = false,
        ["enableNpNonTargetAlphaTargetOnly"] = true,
        ["targetIndicatorTestMode"] = false,
        ["targetIndicatorColorNameplateRGB"] = {
        1,
        0,
        0.44,
        },
        ["partyIndicatorModeTwo"] = false,
        ["nameplateMotionSpeed"] = 0.025,
        ["friendlyNpBuffFilterImportantBuffs"] = false,
        ["nameplateDefaultFriendlyWidth"] = 110,
        ["castBarRecolorInterrupt"] = false,
        ["useCustomTextureForSelfMana"] = false,
        ["healerIndicatorTestMode"] = false,
        ["recolorTempHpLoss"] = false,
        ["bgIndicatorShowFlags"] = true,
        ["nameplateDefaultFriendlyHeight"] = 45,
        ["nameplateAurasFriendlyCenteredAnchor"] = false,
        ["fadeOutNPCWhitelistOn"] = false,
        ["totemIndicator"] = true,
        ["npcTitleColorRGB"] = {
        1,
        0.85,
        0,
        },
        ["normalCastbarForEmpoweredCasts"] = true,
        ["castBarCastColor"] = {
        1,
        0.8431373238563538,
        0.2000000178813934,
        },
        ["personalNpBuffFilterBlacklist"] = true,
        ["classIndicatorAlwaysShowPet"] = false,
        ["nameplateOverlapVScale"] = 1.1,
        ["nameplateAuraDebuffScale"] = 1,
        ["changeNpHpBgColor"] = false,
        ["raidmarkIndicatorYPos"] = 0,
        ["classIndicatorFriendlyAnchor"] = "TOP",
        ["healthNumbersNpcs"] = true,
        ["healthNumbersPlayers"] = true,
        ["healerIndicatorBgOnly"] = false,
        ["showTotemIndicatorCooldownSwipe"] = true,
        ["nameplateMaxScale"] = 0.9,
        ["friendlyNameplatesOnlyInDungeons"] = false,
        ["bgIndicatorTestMode"] = false,
        ["nameplateDefaultLargeEnemyWidth"] = 154,
        ["partyPointerAnchor"] = "TOP",
        ["classicRetailNameplates"] = true,
        ["castBarRecolor"] = false,
        ["enemyClassColorName"] = false,
        ["fadeOutNPCOnlyFadeSecondaryPets"] = true,
        ["fakeNameFriendlyXPos"] = 0,
        ["old_defaultNamePlateFont"] = "Fonts\\FRIZQT__.TTF",
        ["toggleNamesOffDuringPVE"] = false,
        ["classIndicatorCCAuras"] = true,
        ["personalNpBuffFilterWatchList"] = true,
        ["friendlyNpdeBuffFilterLessMinite"] = false,
        ["enemyColorNameRGB"] = {
        1,
        0,
        0,
        },
        ["hideCastbarEnemy"] = false,
        ["totemListUpdateTWW5"] = true,
        ["friendlyHealthBarColor"] = false,
        ["importantCCSilenceGlowRGB"] = {
        ["a"] = 1,
        ["r"] = 1,
        ["g"] = 0.874,
        ["b"] = 0,
        },
        ["partyPointerBgOnly"] = true,
        ["buffIconYPos"] = 0,
        ["absorbIndicatorTestMode"] = false,
        ["npAuraBuffsRGB"] = {
        0,
        0.67,
        1,
        },
        ["classIconAlwaysShowHealer"] = true,
        ["bgIndicatorAnchor"] = "BOTTOM",
        ["arenaIdAnchorRaiseStrata"] = false,
        ["disableImportantAurasOnSelf"] = true,
        ["petIndicatorColorHealthbar"] = false,
        ["hpHeightSelf"] = 10.8,
        ["nameplateMotionSpeedScale"] = 0.03,
        ["hideCastbarFriendly"] = false,
        ["nameplateKeyAurasYPos"] = 0,
        ["classIconAlwaysShowBgObj"] = true,
        ["nameplateLargerScale"] = "1.2",
        ["healerIndicatorEnemyYPos"] = 0,
        ["nameplateAuraDebuffSelfScale"] = 1,
        ["npAuraCurseRGB"] = {
        0.47,
        0,
        0.78,
        },
        ["arenaIDScale"] = 1,
        ["focusTargetIndicator"] = false,
        ["instantComboPoints"] = true,
        ["classIndicatorTank"] = true,
        ["executeIndicatorTestMode"] = false,
        ["nameplateNonTargetAlpha"] = 0.5,
        ["friendlyNpdeBuffFilterOnlyMe"] = false,
        ["auraWhitelistAlphaUpdated"] = true,
        ["friendlyColorNameRGB"] = {
        1,
        1,
        1,
        },
        ["importantCCDisarmGlowRGB"] = {
        ["a"] = 1,
        ["r"] = 1,
        ["g"] = 0.874,
        ["b"] = 0,
        },
        ["partyPointerScale"] = 1.25,
        ["arenaSpecYPos"] = 0,
        ["fadeOutNPCsList"] = {
        {
        ["id"] = 226269,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Charhound (Warlock)",
        ["comment"] = "",
        },
        {
        ["id"] = 26125,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "DK pet",
        ["comment"] = "",
        },
        {
        ["id"] = 228224,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Fenryr (Hunter)",
        ["comment"] = "",
        },
        {
        ["id"] = 226268,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Gloomhound (Warlock)",
        ["comment"] = "",
        },
        {
        ["id"] = 228226,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Hati (Hunter)",
        ["comment"] = "",
        },
        {
        ["id"] = 221632,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Mograine (DK)",
        ["comment"] = "",
        },
        {
        ["id"] = 69792,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Monk SEF Image (Green)",
        ["comment"] = "",
        },
        {
        ["id"] = 69791,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Monk SEF Image (Red)",
        ["comment"] = "",
        },
        {
        ["id"] = 221634,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Nazgrim (DK)",
        ["comment"] = "",
        },
        {
        ["id"] = 103822,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Treant",
        ["comment"] = "",
        },
        {
        ["id"] = 221635,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Trollbane (DK)",
        ["comment"] = "",
        },
        {
        ["id"] = 135816,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Vilefiend (Warlock)",
        ["comment"] = "",
        },
        {
        ["id"] = 192337,
        ["entryColors"] = {
        ["text"] = {
        ["r"] = 0,
        ["g"] = 1,
        ["b"] = 0,
        },
        },
        ["name"] = "Void Tendril (Spriest)",
        ["comment"] = "",
        },
        {
        ["id"] = 208441,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Water Elemental (Mage)",
        ["comment"] = "",
        },
        {
        ["id"] = 221633,
        ["entryColors"] = {
        ["text"] = {
        ["b"] = 0,
        ["g"] = 1,
        ["r"] = 0,
        },
        },
        ["name"] = "Whitemane (DK)",
        ["comment"] = "",
        },
        },
        ["petIndicatorColorHealthbarRGB"] = {
        0.03,
        0.35,
        0,
        },
        ["otherNpBuffPurgeGlow"] = false,
        ["friendlyNpBuffEnable"] = false,
        ["version"] = "1.00",
        ["dpsOrHealTargetAggroColorRGB"] = {
        1,
        0,
        0,
        1,
        },
        ["hideCastbar"] = false,
        ["petIndicatorXPos"] = 0,
        ["nameplateAuraTestMode"] = false,
        ["enlargeAllCC"] = true,
        ["npColorAuraBorder"] = false,
        ["ccIconYPos"] = 0,
        ["healthNumbersCombined"] = false,
        ["hidePersonalManaFX"] = false,
        ["importantCCSilenceGlow"] = true,
        ["classIndicatorBackgroundSize"] = 1,
        ["friendlyHealthBarColorNpc"] = false,
        ["defaultNpAuraCdSize"] = 0.5,
        ["nameplateGlobalScale"] = 1,
        ["nameplateAuraAnchor"] = "BOTTOMLEFT",
        ["importantCCFullGlow"] = true,
        ["targetHighlightFix"] = false,
        ["nameplateAuraRowFriendlyAmount"] = 6,
        ["nameplateMaxAlphaDistance"] = "40",
        ["nameplatePersonalBorderSize"] = 1,
        ["partyPointerClassColor"] = true,
        ["buffIconAnchor"] = "LEFT",
        ["executeIndicator"] = false,
        ["ccIconXPosXPos"] = 0,
        ["buffIconScale"] = 1.65,
        ["ccIconXPos"] = 0,
        ["nameplateAuraTypeGap"] = 0,
        ["friendlyNpdeBuffFilterBlizzard"] = false,
        ["arenaIndicatorModeOne"] = true,
        ["nameplateDebuffPaddingScale"] = 15,
        ["nameplateAuraHideCooldownNumbers"] = false,
        ["skipUpdateMsg"] = true,
        ["npcColorTrivial"] = {
        0.37,
        0.12,
        0.1,
        1,
        },
        ["maxAurasOnNameplate"] = 12,
        ["friendlyNameplatesOnlyInArena"] = true,
        ["firstSaveComplete"] = true,
        ["npcColorMiniboss"] = {
        1,
        0,
        1,
        1,
        },
    }

    if not SkillCappedBackupDB.BetterBlizzPlatesDB then
        SkillCappedBackupDB.BetterBlizzPlatesDB = SC:DeepCopy(BetterBlizzPlatesDB)
        SkillCappedBackupDB.addonBackupTimes["BetterBlizzPlates"] = SC:GetDateAndTime()
    end

    C_CVar.SetCVar("nameplateShowSelf", "1")

    BetterBlizzPlatesDB = scBetterBlizzPlatesDB
    BetterBlizzPlatesDB.scStart = true
    BetterBlizzPlatesDB.skipUpdateMsg = true
    BetterBlizzPlatesDB.skipCVarsPlater = true
    BetterBlizzPlatesDB.skipBugWarning = true

    C_CVar.SetCVarBitfield("nameplateEnemyPlayerAuraDisplay", Enum.NamePlateEnemyPlayerAuraDisplay.Buffs, false)
    C_CVar.SetCVarBitfield("nameplateEnemyPlayerAuraDisplay", Enum.NamePlateEnemyPlayerAuraDisplay.Debuffs, true)
    C_CVar.SetCVarBitfield("nameplateEnemyPlayerAuraDisplay", Enum.NamePlateEnemyPlayerAuraDisplay.LossOfControl, false)

    C_CVar.SetCVarBitfield("nameplateEnemyNpcAuraDisplay", Enum.NamePlateEnemyNpcAuraDisplay.Buffs, false)
    C_CVar.SetCVarBitfield("nameplateEnemyNpcAuraDisplay", Enum.NamePlateEnemyNpcAuraDisplay.Debuffs, true)
    C_CVar.SetCVarBitfield("nameplateEnemyNpcAuraDisplay", Enum.NamePlateEnemyNpcAuraDisplay.CrowdControl, false)

    C_CVar.SetCVarBitfield("nameplateFriendlyPlayerAuraDisplay", Enum.NamePlateFriendlyPlayerAuraDisplay.Buffs, false)
    C_CVar.SetCVarBitfield("nameplateFriendlyPlayerAuraDisplay", Enum.NamePlateFriendlyPlayerAuraDisplay.Debuffs, false)
    C_CVar.SetCVarBitfield("nameplateFriendlyPlayerAuraDisplay", Enum.NamePlateFriendlyPlayerAuraDisplay.LossOfControl, false)

    C_CVar.SetCVarBitfield("nameplateInfoDisplay", Enum.NamePlateInfoDisplay.CurrentHealthPercent, false)
    C_CVar.SetCVarBitfield("nameplateInfoDisplay", Enum.NamePlateInfoDisplay.CurrentHealthValue, false)
    C_CVar.SetCVarBitfield("nameplateInfoDisplay", Enum.NamePlateInfoDisplay.RarityIcon, true)

    C_CVar.SetCVarBitfield("nameplateThreatDisplay", Enum.NamePlateThreatDisplay.Progressive, false)
    C_CVar.SetCVarBitfield("nameplateThreatDisplay", Enum.NamePlateThreatDisplay.Flash, false)
    C_CVar.SetCVarBitfield("nameplateThreatDisplay", Enum.NamePlateThreatDisplay.HealthBarColor, false)

    C_CVar.SetCVarBitfield("nameplateCastBarDisplay", Enum.NamePlateCastBarDisplay.SpellName, true)
    C_CVar.SetCVarBitfield("nameplateCastBarDisplay", Enum.NamePlateCastBarDisplay.SpellIcon, true)
    C_CVar.SetCVarBitfield("nameplateCastBarDisplay", Enum.NamePlateCastBarDisplay.SpellTarget, false)
    C_CVar.SetCVarBitfield("nameplateCastBarDisplay", Enum.NamePlateCastBarDisplay.HighlightImportantCasts, true)
    C_CVar.SetCVarBitfield("nameplateCastBarDisplay", Enum.NamePlateCastBarDisplay.HighlightWhenCastTarget, true)

    C_CVar.SetCVarBitfield("nameplateSimplifiedTypes", Enum.NamePlateSimplifiedType.Minion, false)
    C_CVar.SetCVarBitfield("nameplateSimplifiedTypes", Enum.NamePlateSimplifiedType.MinusMob, false)
    C_CVar.SetCVarBitfield("nameplateSimplifiedTypes", Enum.NamePlateSimplifiedType.FriendlyPlayer, false)
    C_CVar.SetCVarBitfield("nameplateSimplifiedTypes", Enum.NamePlateSimplifiedType.FriendlyNpc, false)

    C_CVar.SetCVarBitfield("nameplateStackingTypes", Enum.NamePlateStackType.Enemy, true)
    C_CVar.SetCVarBitfield("nameplateStackingTypes", Enum.NamePlateStackType.Friendly, false)
end