local AddonName, SkillCapped = ...
local SC = SkillCapped

function SC:BetterBlizzFramesDB()
    local scBetterBlizzFramesDB = {
        ["rpNamesFirst"] = true,
        ["customCode"] = "",
        ["queueTimerWarningTime"] = 6,
        ["targetEnlargeAuraFriendly"] = true,
        ["targetEnlargeAuraEnemy"] = true,
        ["partyFrameRangeAlpha"] = 0.55,
        ["petCastBarWidth"] = 103,
        ["targetCompactAura"] = true,
        ["gladWinTracker"] = true,
        ["powerColorENERGY"] = {
        1,
        1,
        0,
        1,
        },
        ["targetToTYPos"] = 0,
        ["focusCastbarIconXPos"] = 0,
        ["petCastBarScale"] = 1,
        ["powerColorSTAGGER"] = {
        0.52,
        1,
        0.52,
        1,
        },
        ["focusCastbarIconYPos"] = 0,
        ["enemyHealthColor"] = {
        1,
        0,
        0,
        1,
        },
        ["playerAbsorbAnchor"] = "TOP",
        ["focusEnlargeAuraFriendly"] = true,
        ["queueTimerWarning"] = false,
        ["useOnePowerColor"] = false,
        ["hideTargetReputationColor"] = true,
        ["enableBigDebuffs"] = false,
        ["focusAuraGlows"] = true,
        ["focusCastBarIconScale"] = 1,
        ["racialIndicatorYPos"] = 0,
        ["playerCastBarTimer"] = false,
        ["printAuraSpellIds"] = false,
        ["classColorHUNTER"] = {
        0.67,
        0.83,
        0.45,
        1,
        },
        ["queueTimerID"] = 567458,
        ["targetBuffFilterBlacklist"] = true,
        ["targetImportantAuraGlow"] = false,
        ["powerColorLUNAR_POWER"] = {
        0.3,
        0.52,
        0.9,
        1,
        },
        ["opBarriersOn"] = true,
        ["focusdeBuffEnable"] = true,
        ["PlayerAuraFramedeBuffEnable"] = true,
        ["combatIndicatorShowSap"] = false,
        ["queueTimer"] = true,
        ["castBarInterruptIconTarget"] = true,
        ["classColorWARRIOR"] = {
        0.78,
        0.61,
        0.43,
        1,
        },
        ["focusToTAdjustmentOffsetY"] = 0,
        ["combatIndicatorXPos"] = 0,
        ["hideMinimap"] = false,
        ["partyRaidFrameBackgroundManaColor"] = {
        0,
        0,
        0,
        0.75,
        },
        ["auraWhitelistColorsUpdated"] = true,
        ["hideTargetToTName"] = false,
        ["playerCastBarWidth"] = 208,
        ["auraTypeGap"] = 4,
        ["targetToTAdjustmentOffsetY"] = 0,
        ["changePartyFrameRangeAlpha"] = true,
        ["reopenOptions"] = false,
        ["hasSaved"] = true,
        ["powerColorEBON_MIGHT"] = {
        0.9,
        0.55,
        0.3,
        1,
        },
        ["powerColorINSANITY"] = {
        0.4,
        0,
        0.8,
        1,
        },
        ["hasCheckedUi"] = true,
        ["targetCombatIndicator"] = true,
        ["actionBarFontColorRGB"] = {
        1,
        1,
        1,
        1,
        },
        ["hideFocusReputationColor"] = true,
        ["petCastBarHeight"] = 10,
        ["racialIndicatorScale"] = 1,
        ["auraWhitelist"] = {
        ["example aura :3 (delete me)"] = {
        ["name"] = "Example Aura :3 (delete me)",
        ["color"] = {
        0,
        1,
        0,
        1,
        },
        },
        },
        ["hidePlayerRestGlow"] = false,
        ["hidePlayerName"] = false,
        ["allowLargeAuraFirst"] = true,
        ["absorbIndicator"] = false,
        ["queueTimerAudio"] = false,
        ["hideCombatIcon"] = true,
        ["maxDebuffFrameDebuffs"] = 16,
        ["showPartyCastBarIcon"] = true,
        ["absorbIndicatorScale"] = 1,
        ["fadeMicroMenuExceptQueue"] = true,
        ["lossOfControlScale"] = 1,
        ["focusdeBuffFilterAll"] = false,
        ["playerEliteFrameMode"] = 1,
        ["overShieldsCompact"] = false,
        ["frameAuraRowAmount"] = 0,
        ["targetdeBuffEnable"] = true,
        ["partyCastBarTimer"] = false,
        ["overShieldsUnitFrames"] = false,
        ["enlargedAuraSize"] = 1.4,
        ["focusCombatIndicator"] = true,
        ["focusCastBarScale"] = 1,
        ["partyRaidFrameBackgroundHealthColor"] = {
        0,
        0,
        0,
        0.75,
        },
        ["targetdeBuffFilterLessMinite"] = false,
        ["partyCastBarHeight"] = 12,
        ["focusPrestigeBadgeAlpha"] = true,
        ["focusdeBuffFilterBlacklist"] = true,
        ["hidePlayerRoleIcon"] = true,
        ["playerBuffFilterBlacklist"] = true,
        ["optimizedAuraLists"] = true,
        ["playerAbsorbYPos"] = 0,
        ["targetRacialIndicator"] = true,
        ["targetBuffFilterAll"] = true,
        ["partyCastbarIconXPos"] = 0,
        ["druidAlwaysShowCombos"] = true,
        ["targetAndFocusArenaNamePartyOverride"] = true,
        ["focusCastBarTimer"] = false,
        ["hideArenaFrames"] = true,
        ["filterGladiusSpam"] = true,
        ["changePurgeTextureColor"] = true,
        ["focusToTCastbarAdjustment"] = true,
        ["targetCastBarHeight"] = 10,
        ["moveResourceToTargetPaladinBG"] = true,
        ["hideFocusToTDebuffs"] = true,
        ["castBarInterruptHighlighterEndTime"] = 0.6,
        ["focusImportantAuraGlow"] = false,
        ["playerReputationClassColor"] = true,
        ["focusEnlargeAuraEnemy"] = true,
        ["classColorMONK"] = {
        0,
        1,
        0.59,
        1,
        },
        ["combatIndicatorShowSwords"] = true,
        ["healerIndicatorYPos"] = 0,
        ["castBarInterruptIconAnchor"] = "RIGHT",
        ["petCastBarXPos"] = 0,
        ["racialIndicatorHuman"] = true,
        ["focusBuffFilterLessMinite"] = false,
        ["combatIndicator"] = true,
        ["darkModeCastbars"] = true,
        ["racialIndicatorDarkIronDwarf"] = true,
        ["legacyComboYPos"] = -25,
        ["hideLevelText"] = false,
        ["playerReputationColor"] = false,
        ["focusToTXPosXPos"] = 31,
        ["castBarInterruptHighlighterInterruptRGB"] = {
        0,
        1,
        0,
        },
        ["hideDragonFlying"] = false,
        ["auraBlacklist"] = {
        [418563] = {
        ["id"] = 418563,
        ["name"] = "WoW's 19th Anniversary",
        },
        [186403] = {
        ["id"] = 186403,
        ["name"] = "Sign of Battle",
        },
        ["guild champion"] = {
        ["name"] = "Guild Champion",
        },
        ["sign of the scourge"] = {
        ["name"] = "Sign of the Scourge",
        },
        ["sign of the skirmisher"] = {
        ["name"] = "Sign of the Skirmisher",
        },
        [282559] = {
        ["id"] = 282559,
        ["name"] = "Enlisted",
        },
        ["sign of iron"] = {
        ["name"] = "Sign of Iron",
        },
        [397734] = {
        ["id"] = 397734,
        ["name"] = "Word of a Worthy Ally",
        },
        [32727] = {
        ["id"] = 32727,
        ["name"] = "Arena Preparation",
        },
        [93805] = {
        ["id"] = 93805,
        ["name"] = "Ironforge Champion",
        },
        ["honorless target"] = {
        ["name"] = "Honorless Target",
        },
        ["stormwind champion"] = {
        ["name"] = "Stormwind Champion",
        },
        },
        ["combatIndicatorAnchor"] = "RIGHT",
        ["targetAndFocusAuraScaleScale"] = 1,
        ["castBarInterruptIconDisplayCD"] = true,
        ["raidFrameBgTexture"] = "Solid",
        ["normalCastbarForEmpoweredCasts"] = true,
        ["petCastBarIconScale"] = 1,
        ["targetAndFocusAuraOffsetY"] = 0,
        ["frameAurasXPos"] = 0,
        ["healerIndicatorIcon"] = true,
        ["racialIndicatorXPos"] = 0,
        ["racialIndicatorOrc"] = true,
        ["hidePlayerLeaderIcon"] = true,
        ["targetCastBarWidth"] = 150,
        ["darkModeUi"] = false,
        ["targetAndFocusAuraScale"] = 1,
        ["hiddenIconDirection"] = "BOTTOM",
        ["racialIndicatorDwarf"] = true,
        ["focusdeBuffFilterWatchList"] = false,
        ["hidePlayerCornerIcon"] = true,
        ["powerColorFURY"] = {
        0.788,
        0.259,
        0.992,
        1,
        },
        ["powerColorSOUL_FRAGMENTS"] = {
        0.35,
        0.25,
        0.73,
        1,
        },
        ["singlePowerColor"] = {
        1,
        1,
        1,
        1,
        },
        ["hideChatButtons"] = false,
        ["powerColorCHI"] = {
        0.71,
        1,
        0.92,
        1,
        },
        ["playerCastBarIconScale"] = 1,
        ["targetToTXPos"] = 31,
        ["minimizeObjectiveTracker"] = true,
        ["focusdeBuffFilterLessMinite"] = false,
        ["combatIndicatorScale"] = 1,
        ["absorbIndicatorTestMode"] = false,
        ["legacyComboScale"] = 0.85,
        ["healerIndicatorScale"] = 1,
        ["playerAuraSpacingY"] = 0,
        ["targetdeBuffFilterBlizzard"] = true,
        ["recolorCastbars"] = false,
        ["classColorMAGE"] = {
        0.25,
        0.78,
        0.92,
        1,
        },
        ["castbarChannelColor"] = {
        0,
        1,
        0,
        },
        ["targetAbsorbXPos"] = 0,
        ["cdManagerPriorityList"] = {
        },
        ["filterEmoteSpam"] = false,
        ["targetBuffEnable"] = true,
        ["targetdeBuffFilterAll"] = false,
        ["targetdeBuffFilterBlacklist"] = true,
        ["targetCastbarIconYPos"] = 0,
        ["partyCastBarXPos"] = 0,
        ["combatIndicatorYPos"] = 0,
        ["updates"] = "v1.9.0",
        ["showHiddenAurasIcon"] = true,
        ["neutralHealthColor"] = {
        1,
        1,
        0,
        1,
        },
        ["focusCastBarYPos"] = 0,
        ["partyCastBarScale"] = 1,
        ["playerCastBarTimerCenter"] = false,
        ["maxBuffFrameBuffs"] = 32,
        ["enablePlayerBuffFiltering"] = true,
        ["partyFrameScale"] = 1,
        ["focusToTScale"] = 1,
        ["compactedAuraSize"] = 0.7,
        ["hidePrestigeBadge"] = true,
        ["customHealthbarColors"] = false,
        ["frameAuraWidthGap"] = 0,
        ["hideLossOfControlFrameLines"] = true,
        ["targetBuffFilterPurgeable"] = false,
        ["targetdeBuffPandemicGlow"] = false,
        ["focusAbsorbIcon"] = true,
        ["focusBuffFilterWatchList"] = false,
        ["classColorSHAMAN"] = {
        0,
        0.44,
        0.87,
        1,
        },
        ["playerAbsorbAmount"] = true,
        ["focusBuffFilterAll"] = true,
        ["centerNames"] = false,
        ["showPetCastBarTimer"] = false,
        ["playerAuraFiltering"] = true,
        ["castBarInterruptHighlighterStartPercentage"] = 15,
        ["unitFrameFontColorRGB"] = {
        1,
        1,
        1,
        1,
        },
        ["castBarInterruptIconShowActiveOnly"] = false,
        ["filterNpcArenaSpam"] = true,
        ["customImportantAuraSorting"] = true,
        ["targetPrestigeBadgeAlpha"] = true,
        ["healerIndicatorAnchor"] = "CENTER",
        ["useOneClassColor"] = false,
        ["targetBuffFilterOnlyMe"] = false,
        ["hideRaidFrameManager"] = true,
        ["onlyPandemicAuraMine"] = true,
        ["darkModeColor"] = 0.2,
        ["displayDispelGlowAlways"] = false,
        ["racialIndicatorUndead"] = true,
        ["cleanedAuraBlacklist"] = true,
        ["targetCastBarIconScale"] = 1,
        ["targetCastBarTimer"] = false,
        ["targetToTScale"] = 1,
        ["partyCastBarIconScale"] = 1,
        ["focusBuffFilterBlacklist"] = true,
        ["hideObjectiveTracker"] = true,
        ["classColorPALADIN"] = {
        0.96,
        0.55,
        0.73,
        1,
        },
        ["targetCastbarIconXPos"] = 0,
        ["classColorEVOKER"] = {
        0.2,
        0.58,
        0.5,
        1,
        },
        ["removeRealmNames"] = true,
        ["classColorROGUE"] = {
        1,
        0.96,
        0.41,
        1,
        },
        ["partyCastBarYPos"] = 0,
        ["focusToTXPos"] = 31,
        ["focusEnlargeAura"] = true,
        ["focusBuffFilterOnlyMe"] = false,
        ["partyFrameRangeAlphaSolidBackground"] = true,
        ["petCastbar"] = false,
        ["petCastBarTestMode"] = false,
        ["playerAuraSpacingX"] = 5,
        ["partyCastBarWidth"] = 100,
        ["unitFrameValueFontColorRGB"] = {
        1,
        1,
        1,
        1,
        },
        ["castbarUninterruptableColor"] = {
        0.7,
        0.7,
        0.7,
        },
        ["wasOnLoadingScreen"] = false,
        ["castbarCastColor"] = {
        1,
        0.7,
        0,
        },
        ["targetBuffFilterWatchList"] = false,
        ["hideTargetToTDebuffs"] = true,
        ["focusBuffEnable"] = true,
        ["auraImportantDispelIcon"] = true,
        ["targetBuffFilterLessMinite"] = false,
        ["auraToggleIconTexture"] = 134430,
        ["classColorPRIEST"] = {
        1,
        1,
        1,
        1,
        },
        ["racialIndicator"] = false,
        ["targetToTCastbarAdjustment"] = true,
        ["overShields"] = false,
        ["playerCastbarIconYPos"] = 0,
        ["targetdeBuffFilterOnlyMe"] = false,
        ["focusCastBarWidth"] = 150,
        ["cdManagerBlacklist"] = {
        },
        ["healerIndicatorXPos"] = 0,
        ["targetToTXPosXPos"] = 31,
        ["customPowerColors"] = false,
        ["castBarInterruptIconYPos"] = 0,
        ["petCastBarYPos"] = 0,
        ["hidePlayerRestAnimation"] = true,
        ["castBarInterruptHighlighterEndPercentage"] = 80,
        ["castBarInterruptIconFocus"] = true,
        ["unitFrameBgTextureColor"] = {
        0,
        0,
        0,
        0.5,
        },
        ["auraStackSize"] = 1,
        ["targetAbsorbAmount"] = true,
        ["targetAndFocusAuraOffsetX"] = 0,
        ["instantComboPoints"] = true,
        ["targetAndFocusVerticalGap"] = 4,
        ["castBarDelayedInterruptColor"] = {
        1,
        0.4784314036369324,
        0.9568628072738647,
        },
        ["playerCombatIndicator"] = true,
        ["targetEnlargeAura"] = true,
        ["surrenderArena"] = true,
        ["powerColorFOCUS"] = {
        1,
        0.5,
        0.25,
        1,
        },
        ["frameAuraHeightGap"] = 0,
        ["legacyComboXPos"] = -28,
        ["focusToTAnchor"] = "BOTTOMRIGHT",
        ["focusRacialIndicator"] = true,
        ["focusAbsorbAmount"] = true,
        ["PlayerAuraFrameBuffEnable"] = true,
        ["darkModeUiAura"] = true,
        ["purgeTextureColorRGB"] = {
        0,
        0.92,
        1,
        0.85,
        },
        ["PlayerAuraFramedeBuffFilterWatchList"] = false,
        ["castBarInterruptIconScale"] = 1,
        ["maxTargetBuffs"] = 32,
        ["enablePlayerDebuffFiltering"] = false,
        ["racialIndicatorNelf"] = true,
        ["PlayerAuraFrameBuffFilterWatchList"] = false,
        ["frameAurasYPos"] = 0,
        ["targetAuraGlows"] = true,
        ["targetAbsorbAnchor"] = "TOP",
        ["focusCastBarXPos"] = 0,
        ["focusdeBuffFilterOnlyMe"] = false,
        ["uiWidgetPowerBarScale"] = 1,
        ["castBarInterruptHighlighterDontInterruptRGB"] = {
        1,
        0,
        0,
        },
        ["hideFocusCombatGlow"] = false,
        ["castBarInterruptHighlighterStartTime"] = 0.8,
        ["createAltManaBarDruid"] = true,
        ["hideTargetToT"] = false,
        ["powerColorRUNIC_POWER"] = {
        0,
        0.82,
        1,
        1,
        },
        ["focusBuffFilterPurgeable"] = false,
        ["hidePvpTimerText"] = false,
        ["healerIndicatorPortrait"] = true,
        ["classColorDEATHKNIGHT"] = {
        0.77,
        0.12,
        0.23,
        1,
        },
        ["customColorsRaidFrames"] = true,
        ["classColorDRUID"] = {
        1,
        0.49,
        0.04,
        1,
        },
        ["powerColorMAELSTROM"] = {
        0,
        0.5,
        1,
        1,
        },
        ["targetAbsorbIcon"] = true,
        ["targetCastBarXPos"] = 0,
        ["filterTalentSpam"] = true,
        ["customColorsUnitFrames"] = true,
        ["classColorWARLOCK"] = {
        0.53,
        0.53,
        0.93,
        1,
        },
        ["friendlyHealthColor"] = {
        0,
        1,
        0,
        1,
        },
        ["partyCastbarIconYPos"] = 0,
        ["legacyBlueComboPoints"] = true,
        ["playerCastbarIconXPos"] = 0,
        ["focusToTYPos"] = 0,
        ["focusCastBarHeight"] = 10,
        ["playerCastBarHeight"] = 11,
        ["auraWhitelistAlphaUpdated"] = true,
        ["maxAurasOnFrame"] = 0,
        ["targetdeBuffFilterWatchList"] = false,
        ["unitFrameBgTexture"] = "Solid",
        ["powerColorMANA"] = {
        0,
        0,
        1,
        1,
        },
        ["overrideClassColors"] = false,
        ["targetAndFocusAurasPerRow"] = 6,
        ["rpNames"] = true,
        ["darkModeVigor"] = true,
        ["version"] = "1.00",
        ["playerAbsorbIcon"] = true,
        ["castBarInterruptIconXPos"] = 0,
        ["targetAbsorbYPos"] = 0,
        ["powerColorRAGE"] = {
        1,
        0,
        0,
        1,
        },
        ["showPetCastBarIcon"] = true,
        ["maxTargetDebuffs"] = 16,
        ["darkModeActionBars"] = true,
        ["classicCastbarsPlayerBorder"] = true,
        ["skipCustomColorNames"] = false,
        ["classColorDEMONHUNTER"] = {
        0.64,
        0.19,
        0.79,
        1,
        },
        ["hideGroupIndicator"] = true,
        ["unitFrameBgTextureManaColor"] = {
        0,
        0,
        0,
        0.5,
        },
        ["stealthIndicatorPlayer"] = false,
        ["playerAbsorbXPos"] = 0,
        ["targetToTAnchor"] = "BOTTOMRIGHT",
        ["focusCompactAura"] = true,
        ["druidOverstacks"] = true,
        ["targetCastBarYPos"] = 0,
        ["targetAndFocusSmallAuraScale"] = 1,
        ["playerCastBarScale"] = 1,
        ["targetAndFocusHorizontalGap"] = 3,
        ["overShieldsCompactUnitFrames"] = true,
        ["playerdeBuffFilterBlacklist"] = true,
        ["frameAuraScale"] = 0,
        ["customLargeSmallAuraSorting"] = true,
        ["hidePlayerPower"] = false,
        ["castBarNoInterruptColor"] = {
        1,
        0,
        0.01568627543747425,
        },
        ["singleClassColor"] = {
        1,
        1,
        1,
        1,
        },
        ["auraCdTextSize"] = 0.55,
        ["hidePartyFrameTitle"] = true,
        ["focusdeBuffPandemicGlow"] = false,
        ["partyCastBarTestMode"] = false,
        ["targetCastBarScale"] = 1,
        ["castBarRecolorInterrupt"] = false,
        ["partyFrameFontColorRGB"] = {
        1,
        1,
        1,
        1,
        },
        ["focusdeBuffFilterBlizzard"] = true,
        ["increaseAuraStrata"] = true,
    }

    if not SkillCappedBackupDB.BetterBlizzFramesDB then
        SkillCappedBackupDB.BetterBlizzFramesDB = SC:DeepCopy(BetterBlizzFramesDB)
        SkillCappedBackupDB.addonBackupTimes["BetterBlizzFrames"] = SC:GetDateAndTime()
    end

    BetterBlizzFramesDB = scBetterBlizzFramesDB
    BetterBlizzFramesDB.skipUpdateMsg = true
    BetterBlizzFramesDB.skipBugWarning = true
end