-- RenownData.lua
-- Generated by HousingCodex scraper on 2026-03-17 12:00
-- DO NOT EDIT - This file is auto-generated

local ADDON_NAME, addon = ...

addon.RenownSourceData = {
    -- =====================================================================
    -- Classic
    -- =====================================================================
    [72] = {
        label = "Stormwind",
        kind = "standard",
        expansionKey = "EXPANSION_CLASSIC",
        factionSide = "Alliance",
        group = nil,
        requiredStanding = "Friendly",
        vendors = {
            { npcId = 49877, name = "Captain Lancy Revshon", zone = "Stormwind City" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Friendly" },
        },
    },
    [47] = {
        label = "Ironforge",
        kind = "standard",
        expansionKey = "EXPANSION_CLASSIC",
        factionSide = "Alliance",
        group = nil,
        requiredStanding = "Friendly",
        vendors = {
            { npcId = 50309, name = "Captain Stonehelm", zone = "Ironforge" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Friendly" },
        },
    },
    -- =====================================================================
    -- The Burning Crusade
    -- =====================================================================
    [922] = {
        label = "Tranquillien",
        kind = "standard",
        expansionKey = "EXPANSION_TBC",
        factionSide = "Horde",
        group = nil,
        requiredStanding = "Exalted",
        vendors = {
            { npcId = 16528, name = "Provisioner Vredigar", zone = "Ghostlands" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Exalted" },
            { itemId = 0, decorId = nil, requiredStanding = "Exalted" },
        },
    },
    -- =====================================================================
    -- Cataclysm
    -- =====================================================================
    [1134] = {
        label = "Gilneas",
        kind = "standard",
        expansionKey = "EXPANSION_CATA",
        factionSide = "Alliance",
        group = nil,
        requiredStanding = "Honored",
        vendors = {
            { npcId = 50307, name = "Lord Candren", zone = "Darnassus" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Honored" },
        },
    },
    [1174] = {
        label = "Wildhammer Clan",
        kind = "standard",
        expansionKey = "EXPANSION_CATA",
        factionSide = "Alliance",
        group = nil,
        requiredStanding = "Honored",
        vendors = {
            { npcId = 49386, name = "Craw MacGraw", zone = "Twilight Highlands" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Honored" },
        },
    },
    -- =====================================================================
    -- Mists of Pandaria
    -- =====================================================================
    [1273] = {
        label = "Jogu the Drunk",
        kind = "friendship",
        expansionKey = "EXPANSION_MOP",
        factionSide = nil,
        group = "The Tillers",
        requiredStanding = "Good Friend",
        requiredRankLevel = 5, -- Good Friend = rank 5 of 6 (verify in-game)
        vendors = {
            { npcId = 58706, name = "Gina Mudclaw", zone = "Valley of the Four Winds" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Good Friend", requiredRankLevel = 5 },
        },
    },
    [1283] = {
        label = "Farmer Fung",
        kind = "friendship",
        expansionKey = "EXPANSION_MOP",
        factionSide = nil,
        group = "The Tillers",
        requiredStanding = "Good Friend",
        requiredRankLevel = 5,
        vendors = {
            { npcId = 58706, name = "Gina Mudclaw", zone = "Valley of the Four Winds" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Good Friend", requiredRankLevel = 5 },
        },
    },
    [1275] = {
        label = "Ella",
        kind = "friendship",
        expansionKey = "EXPANSION_MOP",
        factionSide = nil,
        group = "The Tillers",
        requiredStanding = "Good Friend",
        requiredRankLevel = 5,
        vendors = {
            { npcId = 58706, name = "Gina Mudclaw", zone = "Valley of the Four Winds" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Good Friend", requiredRankLevel = 5 },
        },
    },
    [1280] = {
        label = "Tina Mudclaw",
        kind = "friendship",
        expansionKey = "EXPANSION_MOP",
        factionSide = nil,
        group = "The Tillers",
        requiredStanding = "Good Friend",
        requiredRankLevel = 5,
        vendors = {
            { npcId = 58706, name = "Gina Mudclaw", zone = "Valley of the Four Winds" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Good Friend", requiredRankLevel = 5 },
        },
    },
    [1345] = {
        label = "The Lorewalkers",
        kind = "standard",
        expansionKey = "EXPANSION_MOP",
        factionSide = nil,
        group = nil,
        requiredStanding = "Exalted",
        vendors = {
            { npcId = 64605, name = "Tan Shin Tiao", zone = "Vale of Eternal Blossoms" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Exalted" },
        },
    },
    [1271] = {
        label = "Order of the Cloud Serpent",
        kind = "standard",
        expansionKey = "EXPANSION_MOP",
        factionSide = nil,
        group = nil,
        requiredStanding = "Exalted",
        vendors = {
            { npcId = 58414, name = "San Redscale", zone = "Jade Forest" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Exalted" },
        },
    },
    -- =====================================================================
    -- Warlords of Draenor
    -- =====================================================================
    [1731] = {
        label = "Council of Exarchs",
        kind = "standard",
        expansionKey = "EXPANSION_WOD",
        factionSide = "Alliance",
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 85932, name = "Vindicator Nuurem", zone = "Stormshield" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    [1710] = {
        label = "Sha'tari Defense",
        kind = "standard",
        expansionKey = "EXPANSION_WOD",
        factionSide = "Alliance",
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 85427, name = "Maaria", zone = "Talador" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    [1708] = {
        label = "Laughing Skull Orcs",
        kind = "standard",
        expansionKey = "EXPANSION_WOD",
        factionSide = "Horde",
        group = nil,
        requiredStanding = "Friendly",
        vendors = {
            { npcId = 87015, name = "Kil'rip", zone = "Frostwall Garrison" },
        },
        rewards = {
            { itemId = 0, decorId = 1317, requiredStanding = "Friendly" },
            { itemId = 0, decorId = 1322, requiredStanding = "Friendly" },
        },
    },
    [1515] = {
        label = "Arakkoa Outcasts",
        kind = "standard",
        expansionKey = "EXPANSION_WOD",
        factionSide = nil,
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 85946, name = "Shadow-Sage Brakoss", zone = "Spires of Arak" },
            { npcId = 86037, name = "Ravenspeaker Skeega", zone = "Spires of Arak" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    -- =====================================================================
    -- Legion
    -- =====================================================================
    [1828] = {
        label = "Highmountain Tribe",
        kind = "standard",
        expansionKey = "EXPANSION_LEGION",
        factionSide = nil,
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 106902, name = "Ransa Greyfeather", zone = "Thunder Totem" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    [1883] = {
        label = "Dreamweavers",
        kind = "standard",
        expansionKey = "EXPANSION_LEGION",
        factionSide = nil,
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 106901, name = "Sylvia Hartshorn", zone = "Val'sharah" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    [1859] = {
        label = "The Nightfallen",
        kind = "standard",
        expansionKey = "EXPANSION_LEGION",
        factionSide = nil,
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 115736, name = "First Arcanist Thalyssra", zone = "Shal'Aran" },
            { npcId = 248594, name = "Sundries Merchant", zone = "Suramar" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    -- =====================================================================
    -- Battle for Azeroth
    -- =====================================================================
    [2162] = {
        label = "Storm's Wake",
        kind = "standard",
        expansionKey = "EXPANSION_BFA",
        factionSide = "Alliance",
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 252313, name = "Caspian", zone = "Stormsong Valley" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Friendly" },
            { itemId = 0, decorId = nil, requiredStanding = "Honored" },
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    [2160] = {
        label = "Proudmoore Admiralty",
        kind = "standard",
        expansionKey = "EXPANSION_BFA",
        factionSide = "Alliance",
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 135808, name = "Provisioner Fray", zone = "Boralus" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Friendly" },
            { itemId = 0, decorId = nil, requiredStanding = "Honored" },
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    [2103] = {
        label = "Zandalari Empire",
        kind = "standard",
        expansionKey = "EXPANSION_BFA",
        factionSide = "Horde",
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 252326, name = "T'lama", zone = "Dazar'alor" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Friendly" },
            { itemId = 0, decorId = nil, requiredStanding = "Honored" },
            { itemId = 0, decorId = nil, requiredStanding = "Honored" },
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    [2156] = {
        label = "Talanji's Expedition",
        kind = "standard",
        expansionKey = "EXPANSION_BFA",
        factionSide = "Horde",
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 135459, name = "Provisioner Lija", zone = "Nazmir" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    [2157] = {
        label = "The Honorbound",
        kind = "standard",
        expansionKey = "EXPANSION_BFA",
        factionSide = "Horde",
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 148924, name = "Provisioner Mukra", zone = "Zuldazar" },
            { npcId = 251921, name = "Arcanist Peroleth", zone = "Zuldazar" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    [2391] = {
        label = "Rustbolt Resistance",
        kind = "standard",
        expansionKey = "EXPANSION_BFA",
        factionSide = nil,
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 150716, name = "Stolen Royal Vendorbot", zone = "Mechagon" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    -- =====================================================================
    -- Dragonflight
    -- =====================================================================
    [2510] = {
        label = "Valdrakken Accord",
        kind = "renown",
        expansionKey = "EXPANSION_DF",
        factionSide = nil,
        group = nil,
        requiredStanding = "Renown 20",
        vendors = {
            { npcId = 193015, name = "Unatos", zone = "Valdrakken" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Renown 3" },
            { itemId = 0, decorId = nil, requiredStanding = "Renown 6" },
            { itemId = 0, decorId = nil, requiredStanding = "Renown 14" },
            { itemId = 0, decorId = nil, requiredStanding = "Renown 20" },
        },
    },
    [2507] = {
        label = "Dragonscale Expedition",
        kind = "renown",
        expansionKey = "EXPANSION_DF",
        factionSide = nil,
        group = nil,
        requiredStanding = "Renown 15",
        vendors = {
            { npcId = 189226, name = "Cataloger Jakes", zone = "Waking Shores" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Renown 15" },
        },
    },
    -- =====================================================================
    -- The War Within
    -- =====================================================================
    [2675] = {
        label = "Blackwater Cartel",
        kind = "standard",
        expansionKey = "EXPANSION_TWW",
        factionSide = nil,
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 231405, name = "Boatswain Hardee", zone = "Undermine" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Honored" },
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    [2677] = {
        label = "Steamwheedle Cartel",
        kind = "standard",
        expansionKey = "EXPANSION_TWW",
        factionSide = nil,
        group = nil,
        requiredStanding = "Honored",
        vendors = {
            { npcId = 231408, name = "Lab Assistant Laszly", zone = "Undermine" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Friendly" },
            { itemId = 0, decorId = nil, requiredStanding = "Honored" },
        },
    },
    [2673] = {
        label = "Bilgewater Cartel",
        kind = "standard",
        expansionKey = "EXPANSION_TWW",
        factionSide = nil,
        group = nil,
        requiredStanding = "Honored",
        vendors = {
            { npcId = 231406, name = "Rocco Razzboom", zone = "Undermine" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Honored" },
            { itemId = 0, decorId = nil, requiredStanding = "Honored" },
        },
    },
    [2671] = {
        label = "Venture Company",
        kind = "standard",
        expansionKey = "EXPANSION_TWW",
        factionSide = nil,
        group = nil,
        requiredStanding = "Revered",
        vendors = {
            { npcId = 231407, name = "Shredz the Scrapper", zone = "Undermine" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Honored" },
            { itemId = 0, decorId = nil, requiredStanding = "Revered" },
        },
    },
    [2669] = {
        label = "Darkfuse Solutions",
        kind = "standard",
        expansionKey = "EXPANSION_TWW",
        factionSide = nil,
        group = nil,
        requiredStanding = "Honored",
        vendors = {
            { npcId = 231396, name = "Sitch Lowdown", zone = "Undermine" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Friendly" },
            { itemId = 0, decorId = nil, requiredStanding = "Honored" },
        },
    },
    [2688] = {
        label = "Flame's Radiance",
        kind = "renown",
        expansionKey = "EXPANSION_TWW",
        factionSide = nil,
        group = nil,
        requiredStanding = "Renown 8",
        vendors = {
            { npcId = 240852, name = "Lars Bronsmaelt", zone = "Hallowfall" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Renown 8" },
        },
    },
    [2766] = {
        label = "Brawl'gar Arena",
        kind = "friendship",
        expansionKey = "EXPANSION_TWW",
        factionSide = "Horde",
        group = nil,
        requiredStanding = "Rank 7",
        requiredRankLevel = 7, -- Brawler ranks 1-8 (verify in-game)
        vendors = {
            { npcId = 145695, name = "\"Bad Luck\" Symmes", zone = "Brawl'gar Arena" },
        },
        rewards = {
            { itemId = 0, decorId = 14815, requiredStanding = "Rank 2", requiredRankLevel = 2 },
            { itemId = 0, decorId = 12263, requiredStanding = "Rank 5", requiredRankLevel = 5 },
            { itemId = 0, decorId = 10913, requiredStanding = "Rank 7", requiredRankLevel = 7 },
        },
    },
    [2767] = {
        label = "Bizmo's Brawlpub",
        kind = "friendship",
        expansionKey = "EXPANSION_TWW",
        factionSide = "Alliance",
        group = nil,
        requiredStanding = "Rank 7",
        requiredRankLevel = 7,
        vendors = {
            { npcId = 151941, name = "Dershway the Triggered", zone = "Bizmo's Brawlpub" },
        },
        rewards = {
            { itemId = 0, decorId = 14815, requiredStanding = "Rank 2", requiredRankLevel = 2 },
            { itemId = 0, decorId = 12263, requiredStanding = "Rank 5", requiredRankLevel = 5 },
            { itemId = 0, decorId = 10913, requiredStanding = "Rank 7", requiredRankLevel = 7 },
        },
    },
    -- =====================================================================
    -- Midnight
    -- =====================================================================
    [2699] = {
        label = "The Singularity",
        kind = "renown",
        expansionKey = "EXPANSION_MIDNIGHT",
        factionSide = nil,
        group = nil,
        requiredStanding = "Renown 10",
        vendors = {
            { npcId = 248328, name = "Void Researcher Anomander", zone = "Voidstorm" },
            { npcId = 259922, name = "Void Researcher Aemely", zone = "Voidstorm" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Renown 5" },
            { itemId = 0, decorId = nil, requiredStanding = "Renown 10" },
        },
    },
    [2696] = {
        label = "Amani Tribe",
        kind = "renown",
        expansionKey = "EXPANSION_MIDNIGHT",
        factionSide = nil,
        group = nil,
        requiredStanding = "Renown 10",
        vendors = {
            { npcId = 240279, name = "Magovu", zone = "Zul'Aman" },
            { npcId = 254944, name = "Tajaka Sawtusk", zone = "Zul'Aman" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Renown 5" },
            { itemId = 0, decorId = nil, requiredStanding = "Renown 10" },
        },
    },
    [2704] = {
        label = "Hara'ti",
        kind = "renown",
        expansionKey = "EXPANSION_MIDNIGHT",
        factionSide = nil,
        group = nil,
        requiredStanding = "Renown 10",
        vendors = {
            { npcId = 240407, name = "Naynar", zone = "Harandar" },
            { npcId = 251259, name = "Mothkeeper Wew'tam", zone = "Harandar" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Renown 5" },
            { itemId = 0, decorId = nil, requiredStanding = "Renown 10" },
        },
    },
    [2710] = {
        label = "Silvermoon Court",
        kind = "renown",
        expansionKey = "EXPANSION_MIDNIGHT",
        factionSide = nil,
        group = nil,
        requiredStanding = "Renown 10",
        vendors = {
            { npcId = 240838, name = "Caeris Fairdawn", zone = "Eversong Woods" },
            { npcId = 259864, name = "Sathren Azuredawn", zone = "Eversong Woods" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Renown 5" },
            { itemId = 0, decorId = nil, requiredStanding = "Renown 10" },
        },
    },
    [2711] = {
        label = "The Magisters",
        kind = "standard",
        expansionKey = "EXPANSION_MIDNIGHT",
        factionSide = nil,
        group = nil,
        requiredStanding = "Friendly",
        vendors = {
            { npcId = 242723, name = "Apprentice Diell", zone = "Silvermoon City" },
            { npcId = 242726, name = "Neriv", zone = "Silvermoon City" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Friendly" },
        },
    },
    [2712] = {
        label = "Blood Knights",
        kind = "standard",
        expansionKey = "EXPANSION_MIDNIGHT",
        factionSide = nil,
        group = nil,
        requiredStanding = "Friendly",
        vendors = {
            { npcId = 242725, name = "Armorer Goldcrest", zone = "Silvermoon City" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Friendly" },
        },
    },
    [2713] = {
        label = "Farstriders",
        kind = "standard",
        expansionKey = "EXPANSION_MIDNIGHT",
        factionSide = nil,
        group = nil,
        requiredStanding = "Friendly",
        vendors = {
            { npcId = 242724, name = "Ranger Allorn", zone = "Silvermoon City" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Friendly" },
        },
    },
    [2714] = {
        label = "Shades of the Row",
        kind = "standard",
        expansionKey = "EXPANSION_MIDNIGHT",
        factionSide = nil,
        group = nil,
        requiredStanding = "Friendly",
        vendors = {
            { npcId = 242726, name = "Neriv", zone = "Silvermoon City" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Friendly" },
        },
    },
    [2770] = {
        label = "Slayer's Duellum",
        kind = "standard",
        expansionKey = "EXPANSION_MIDNIGHT",
        factionSide = nil,
        group = nil,
        requiredStanding = "Friendly",
        vendors = {
            { npcId = 258328, name = "Thraxadar", zone = "Masters' Perch" },
        },
        rewards = {
            { itemId = 0, decorId = nil, requiredStanding = "Friendly" },
        },
    },
}
