local AddonName, SkillCapped = ...
local SC = SkillCapped

function SC:BetterBlizzFramesDB()
    local scBetterBlizzFramesDB = {
        ["customCode"] = "",
        ["queueTimerWarningTime"] = 6,
        ["targetEnlargeAuraFriendly"] = true,
        ["targetEnlargeAuraEnemy"] = true,
        ["petCastBarWidth"] = 103,
        ["targetCompactAura"] = true,
        ["partyCastbarShowText"] = true,
        ["playerFrameScale"] = 1,
        ["focusdeBuffFilterBlizzard"] = false,
        ["targetdeBuffFilterBlizzard"] = false,
        ["petCastBarScale"] = 1,
        ["castBarRecolorInterrupt"] = false,
        ["hideFocusCombatGlow"] = false,
        ["targetAbsorbAnchor"] = "TOP",
        ["focusEnlargeAuraFriendly"] = true,
        ["queueTimerWarning"] = false,
        ["hideTargetReputationColor"] = false,
        ["focusAuraGlows"] = true,
        ["focusCastBarIconScale"] = 1,
        ["playerCastBarTimerCenter"] = false,
        ["playerCastBarTimer"] = false,
        ["printAuraSpellIds"] = false,
        ["maxBuffFrameBuffs"] = 32,
        ["queueTimerID"] = 567458,
        ["targetBuffFilterBlacklist"] = true,
        ["targetImportantAuraGlow"] = false,
        ["playerdeBuffFilterBlacklist"] = true,
        ["focusToTScale"] = 1,
        ["PlayerAuraFramedeBuffEnable"] = true,
        ["combatIndicatorShowSap"] = false,
        ["queueTimer"] = true,
        ["castBarInterruptIconTarget"] = true,
        ["focusToTAdjustmentOffsetY"] = 0,
        ["combatIndicatorXPos"] = 0,
        ["targetAndFocusSmallAuraScale"] = 1,
        ["auraWhitelistColorsUpdated"] = true,
        ["hideTargetToTName"] = false,
        ["playerCastBarWidth"] = 208,
        ["auraTypeGap"] = 4,
        ["targetToTAdjustmentOffsetY"] = 0,
        ["maxPlayerAurasPerRow"] = 10,
        ["reopenOptions"] = false,
        ["hasSaved"] = true,
        ["hasCheckedUi"] = true,
        ["targetCombatIndicator"] = true,
        ["targetCastBarYPos"] = 0,
        ["focusCompactAura"] = true,
        ["petCastBarHeight"] = 10,
        ["racialIndicatorScale"] = 1,
        ["interruptIconBorder"] = true,
        ["purgeableAuraSize"] = 1,
        ["auraWhitelist"] = {
        ["example aura :3 (delete me)"] = {
        ["name"] = "Example Aura :3 (delete me)",
        ["color"] = {
        0,
        1,
        0,
        1,
        },
        },
        },
        ["hidePlayerRestGlow"] = false,
        ["hidePlayerName"] = false,
        ["allowLargeAuraFirst"] = true,
        ["absorbIndicator"] = false,
        ["queueTimerAudio"] = false,
        ["stealthIndicatorPlayer"] = false,
        ["maxDebuffFrameDebuffs"] = 16,
        ["showPartyCastBarIcon"] = true,
        ["absorbIndicatorScale"] = 1,
        ["lossOfControlScale"] = 1,
        ["focusdeBuffFilterAll"] = false,
        ["partyCastBarIconScale"] = 1,
        ["overShieldsCompact"] = true,
        ["frameAuraRowAmount"] = 0,
        ["targetdeBuffEnable"] = true,
        ["partyCastBarTimer"] = false,
        ["focusFrameScale"] = 1,
        ["overShieldsUnitFrames"] = true,
        ["playerAbsorbAmount"] = true,
        ["focusCombatIndicator"] = true,
        ["showPetCastBarIcon"] = true,
        ["partyCastBarYPos"] = 0,
        ["targetdeBuffFilterLessMinite"] = false,
        ["partyCastBarHeight"] = 12,
        ["focusPrestigeBadgeAlpha"] = true,
        ["focusdeBuffFilterBlacklist"] = true,
        ["hidePlayerRoleIcon"] = true,
        ["playerBuffFilterBlacklist"] = true,
        ["targetAbsorbYPos"] = 0,
        ["focusCastBarShowBorder"] = true,
        ["playerAbsorbYPos"] = 0,
        ["targetRacialIndicator"] = true,
        ["targetBuffFilterAll"] = true,
        ["partyCastbarIconXPos"] = 0,
        ["targetAndFocusArenaNamePartyOverride"] = true,
        ["focusCastBarTimer"] = false,
        ["hideArenaFrames"] = true,
        ["filterGladiusSpam"] = true,
        ["biggerHealthbars"] = true,
        ["focusToTCastbarAdjustment"] = true,
        ["targetBuffFilterLessMinite"] = false,
        ["hideFocusToTDebuffs"] = true,
        ["castBarInterruptHighlighterEndTime"] = 0.6,
        ["focusImportantAuraGlow"] = false,
        ["playerCastBarYPos"] = 0,
        ["playerReputationClassColor"] = true,
        ["focusEnlargeAuraEnemy"] = true,
        ["castBarInterruptHighlighterEndPercentage"] = 80,
        ["combatIndicatorShowSwords"] = true,
        ["castBarInterruptIconAnchor"] = "RIGHT",
        ["petCastBarXPos"] = 0,
        ["racialIndicatorHuman"] = true,
        ["focusBuffFilterLessMinite"] = false,
        ["castBarInterruptIconXPos"] = 0,
        ["darkModeCastbars"] = true,
        ["legacyComboYPos"] = -9,
        ["hideLevelText"] = false,
        ["partyCastbarIconYPos"] = 0,
        ["focusToTXPosXPos"] = 0,
        ["reduceEditModeSelectionAlpha"] = true,
        ["castBarInterruptHighlighterInterruptRGB"] = {
        0,
        1,
        0,
        },
        ["frameAuraHeightGap"] = 0,
        ["auraBlacklist"] = {
        [418563] = {
        ["id"] = 418563,
        ["name"] = "WoW's 19th Anniversary",
        },
        [186403] = {
        ["id"] = 186403,
        ["name"] = "Sign of Battle",
        },
        ["guild champion"] = {
        ["name"] = "Guild Champion",
        },
        ["sign of the scourge"] = {
        ["name"] = "Sign of the Scourge",
        },
        ["sign of the skirmisher"] = {
        ["name"] = "Sign of the Skirmisher",
        },
        [282559] = {
        ["id"] = 282559,
        ["name"] = "Enlisted",
        },
        ["sign of iron"] = {
        ["name"] = "Sign of Iron",
        },
        [397734] = {
        ["id"] = 397734,
        ["name"] = "Word of a Worthy Ally",
        },
        [32727] = {
        ["id"] = 32727,
        ["name"] = "Arena Preparation",
        },
        [93805] = {
        ["id"] = 93805,
        ["name"] = "Ironforge Champion",
        },
        ["honorless target"] = {
        ["name"] = "Honorless Target",
        },
        ["stormwind champion"] = {
        ["name"] = "Stormwind Champion",
        },
        },
        ["combatIndicatorAnchor"] = "RIGHT",
        ["castBarInterruptIconDisplayCD"] = true,
        ["normalCastbarForEmpoweredCasts"] = true,
        ["petCastBarIconScale"] = 1,
        ["targetAbsorbIcon"] = true,
        ["hidePetText"] = true,
        ["maxTargetDebuffs"] = 16,
        ["racialIndicatorOrc"] = true,
        ["hidePlayerLeaderIcon"] = true,
        ["targetCastBarWidth"] = 150,
        ["darkModeUi"] = true,
        ["targetAndFocusAuraScale"] = 1,
        ["classPortraits"] = true,
        ["hiddenIconDirection"] = "BOTTOM",
        ["mopUpdates"] = true,
        ["playerAuraYOffset"] = 0,
        ["castBarInterruptHighlighterStartPercentage"] = 15,
        ["hidePlayerCornerIcon"] = true,
        ["hideChatButtons"] = false,
        ["focusCastBarXPos"] = 0,
        ["playerAuraImportantGlow"] = true,
        ["playerCastBarIconScale"] = 1,
        ["targetToTXPos"] = 0,
        ["minimizeObjectiveTracker"] = true,
        ["focusdeBuffFilterLessMinite"] = false,
        ["combatIndicatorScale"] = 1,
        ["castBarInterruptHighlighterDontInterruptRGB"] = {
        1,
        0,
        0,
        },
        ["playerAuraSpacingY"] = 0,
        ["hideTargetToT"] = false,
        ["filterEmoteSpam"] = false,
        ["skipUpdateMsg"] = true,
        ["targetCastbarIconYPos"] = 0,
        ["castBarInterruptIconScale"] = 1,
        ["focusToTAnchor"] = "BOTTOMRIGHT",
        ["focusCastBarYPos"] = 0,
        ["targetdeBuffFilterBlacklist"] = true,
        ["petCastBarShowBorder"] = true,
        ["compactedAuraSize"] = 0.7,
        ["targetToTAnchor"] = "BOTTOMRIGHT",
        ["frameAuraWidthGap"] = 0,
        ["targetBuffFilterPurgeable"] = false,
        ["unitFrameBgTextureColor"] = {
        0,
        0,
        0,
        0.5,
        },
        ["showPetCastBarTimer"] = false,
        ["playerAuraFiltering"] = false,
        ["unitFrameFontColorRGB"] = {
        1,
        1,
        1,
        1,
        },
        ["castBarInterruptIconShowActiveOnly"] = false,
        ["playerAuraBuffScale"] = 1,
        ["targetPrestigeBadgeAlpha"] = true,
        ["targetBuffFilterOnlyMe"] = false,
        ["hideRaidFrameManager"] = true,
        ["darkModeColor"] = 0.2,
        ["onlyPandemicAuraMine"] = true,
        ["racialIndicatorUndead"] = true,
        ["targetCastBarIconScale"] = 1,
        ["targetCastBarTimer"] = false,
        ["focusBuffFilterBlacklist"] = true,
        ["targetCastbarIconXPos"] = 0,
        ["focusBuffEnable"] = true,
        ["removeRealmNames"] = true,
        ["targetdeBuffFilterWatchList"] = false,
        ["playerAuraGlows"] = true,
        ["focusEnlargeAura"] = true,
        ["targetAbsorbXPos"] = 0,
        ["focusBuffFilterOnlyMe"] = false,
        ["targetBuffEnable"] = true,
        ["petCastbar"] = false,
        ["targetdeBuffFilterAll"] = false,
        ["petCastBarYPos"] = 0,
        ["optimizedAuraLists"] = true,
        ["unitFrameValueFontColorRGB"] = {
        1,
        1,
        1,
        1,
        },
        ["centerNames"] = false,
        ["wasOnLoadingScreen"] = false,
        ["combatIndicatorYPos"] = 0,
        ["showHiddenAurasIcon"] = true,
        ["hideTargetToTDebuffs"] = true,
        ["hidePlayerPower"] = false,
        ["playerCastBarShowBorder"] = true,
        ["playerAbsorbAnchor"] = "TOP",
        ["darkModeVigor"] = true,
        ["hideDragonFlying"] = true,
        ["enablePlayerBuffFiltering"] = true,
        ["targetToTCastbarAdjustment"] = true,
        ["overShields"] = true,
        ["playerCastbarIconYPos"] = 0,
        ["targetdeBuffFilterOnlyMe"] = false,
        ["focusCastBarWidth"] = 150,
        ["hideLossOfControlFrameLines"] = true,
        ["hideCombatIcon"] = true,
        ["targetToTXPosXPos"] = 0,
        ["focusToTXPos"] = 0,
        ["enableLoCFrame"] = true,
        ["partyCastbarShowBorder"] = true,
        ["hidePlayerRestAnimation"] = true,
        ["raiseTargetCastbarStrata"] = true,
        ["focusBuffFilterWatchList"] = false,
        ["racialIndicator"] = false,
        ["auraStackSize"] = 1,
        ["targetAbsorbAmount"] = true,
        ["targetAndFocusAuraOffsetX"] = 0,
        ["auraToggleIconTexture"] = 134430,
        ["petCastBarShowText"] = true,
        ["castBarDelayedInterruptColor"] = {
        1,
        0.4784314036369324,
        0.9568628072738647,
        },
        ["showCooldownOnLoC"] = true,
        ["actionBarFontColorRGB"] = {
        1,
        1,
        1,
        1,
        },
        ["surrenderArena"] = true,
        ["hideObjectiveTracker"] = true,
        ["targetToTScale"] = 1,
        ["hideFocusReputationColor"] = false,
        ["legacyComboXPos"] = -44,
        ["focusRacialIndicator"] = true,
        ["focusAbsorbAmount"] = true,
        ["PlayerAuraFrameBuffEnable"] = true,
        ["focusAbsorbIcon"] = true,
        ["enlargedAuraSize"] = 1.4,
        ["PlayerAuraFramedeBuffFilterWatchList"] = false,
        ["targetToTYPos"] = 0,
        ["maxTargetBuffs"] = 32,
        ["purgeTextureColorRGB"] = {
        0,
        0.92,
        1,
        0.85,
        },
        ["targetCastBarXPos"] = 0,
        ["PlayerAuraFrameBuffFilterWatchList"] = false,
        ["targetEnlargeAura"] = true,
        ["enablePlayerDebuffFiltering"] = false,
        ["frameAurasYPos"] = 0,
        ["version"] = "1.00",
        ["playerCastbarIconXPos"] = 0,
        ["focusCastbarIconYPos"] = 0,
        ["partyCastBarScale"] = 1,
        ["playerAuraSpacingX"] = 5,
        ["absorbIndicatorTestMode"] = false,
        ["playerReputationColor"] = false,
        ["playerAuraXOffset"] = 0,
        ["maxAurasOnFrame"] = 0,
        ["focusBuffFilterPurgeable"] = false,
        ["hidePvpTimerText"] = false,
        ["auraWhitelistAlphaUpdated"] = true,
        ["playerCastBarHeight"] = 11,
        ["displayDispelGlowAlways"] = false,
        ["legacyComboScale"] = 1,
        ["focusdeBuffEnable"] = true,
        ["updates"] = "v1.9.0",
        ["racialIndicatorNelf"] = true,
        ["filterTalentSpam"] = true,
        ["targetCastBarHeight"] = 10,
        ["targetAndFocusVerticalGap"] = 4,
        ["partyCastBarXPos"] = 0,
        ["castBarInterruptIconFocus"] = true,
        ["castBarInterruptHighlighterStartTime"] = 0.8,
        ["targetAndFocusAuraOffsetY"] = 0,
        ["targetAuraGlows"] = true,
        ["focusCastBarHeight"] = 10,
        ["playerCastBarShowText"] = true,
        ["playerFrameOCDZoom"] = true,
        ["castBarInterruptIconYPos"] = 0,
        ["focusToTYPos"] = 0,
        ["focusCastBarScale"] = 1,
        ["targetAndFocusHorizontalGap"] = 3,
        ["focusdeBuffFilterWatchList"] = false,
        ["targetAndFocusAurasPerRow"] = 6,
        ["customImportantAuraSorting"] = true,
        ["darkModeUiAura"] = true,
        ["focusBuffFilterAll"] = true,
        ["playerAbsorbIcon"] = true,
        ["focusCastbarIconXPos"] = 0,
        ["frameAurasXPos"] = 0,
        ["targetCastBarShowBorder"] = true,
        ["focusCastBarShowText"] = true,
        ["racialIndicatorYPos"] = 0,
        ["darkModeActionBars"] = true,
        ["filterNpcArenaSpam"] = true,
        ["hideMinimap"] = false,
        ["petCastBarTestMode"] = false,
        ["hideGroupIndicator"] = true,
        ["targetdeBuffPandemicGlow"] = false,
        ["combatIndicator"] = true,
        ["playerAbsorbXPos"] = 0,
        ["repositionBuffFrame"] = true,
        ["hidePrestigeBadge"] = true,
        ["castBarNoInterruptColor"] = {
        1,
        0,
        0.01568627543747425,
        },
        ["targetBuffFilterWatchList"] = false,
        ["targetCastBarShowText"] = true,
        ["playerEliteFrameMode"] = 1,
        ["racialIndicatorXPos"] = 0,
        ["overShieldsCompactUnitFrames"] = true,
        ["fixHealthbarText"] = true,
        ["frameAuraScale"] = 0,
        ["customLargeSmallAuraSorting"] = true,
        ["playerCastBarXPos"] = 0,
        ["targetFrameScale"] = 1,
        ["focusdeBuffFilterOnlyMe"] = false,
        ["playerCastBarScale"] = 1,
        ["hidePartyFrameTitle"] = true,
        ["focusdeBuffPandemicGlow"] = false,
        ["partyCastBarTestMode"] = false,
        ["targetCastBarScale"] = 1,
        ["classColorFrames"] = true,
        ["partyFrameFontColorRGB"] = {
        1,
        1,
        1,
        1,
        },
        ["playerCombatIndicator"] = true,
        ["partyCastBarWidth"] = 100,
    }

    if not SkillCappedBackupDB.BetterBlizzFramesDB then
        SkillCappedBackupDB.BetterBlizzFramesDB = SC:DeepCopy(BetterBlizzFramesDB)
        SkillCappedBackupDB.addonBackupTimes["BetterBlizzFrames"] = SC:GetDateAndTime()
    end

    BetterBlizzFramesDB = scBetterBlizzFramesDB
    BetterBlizzFramesDB.scStart = true
end