local AddonName, SkillCapped = ...
local SC = SkillCapped

function SC:BuffOverlayDB()
	local scBuffOverlayDB = {
		["profileKeys"] = {
		[SC:GetPlayerNameAndRealm()] = "SkillCapped",
		},
		["global"] = {
		["dbVer"] = 1,
		},
		["profiles"] = {
		["SkillCapped"] = {
		["bars"] = {
		["Bar1"] = {
		["neverShow"] = false,
		["showCooldownSpiral"] = true,
		["iconScale"] = 0.9,
		["showInBattleground"] = true,
		["iconCount"] = 2,
		["stackCountScale"] = 0.9,
		["maxGroupSize"] = 40,
		["showInArena"] = true,
		["iconBorderSize"] = 1,
		["buffIconBorderColorByDispelType"] = false,
		["showInWorld"] = true,
		["iconBorder"] = true,
		["showInScenario"] = true,
		["iconYOff"] = 0,
		["showInDungeon"] = true,
		["iconXOff"] = 0,
		["iconAlpha"] = 0.8,
		["debuffIconBorderColorByDispelType"] = false,
		["iconSpacing"] = 0,
		["iconAnchor"] = "BOTTOM",
		["id"] = "Bar1",
		["showTooltip"] = false,
		["frameTypes"] = {
		["player"] = true,
		["party"] = true,
		["arena"] = true,
		["assist"] = true,
		["raid"] = true,
		["pet"] = true,
		["tank"] = true,
		},
		["showInRaid"] = true,
		["minGroupSize"] = 0,
		["iconBorderColor"] = {
		["a"] = 1,
		["b"] = 0,
		["g"] = 0,
		["r"] = 0,
		},
		["name"] = "Bar1",
		["showCooldownNumbers"] = false,
		["cooldownNumberScale"] = 1,
		["showStackCount"] = true,
		["iconRelativePoint"] = "CENTER",
		["growDirection"] = "HORIZONTAL",
		},
		},
		["buffs"] = {
		[10278] = {
		["parent"] = 1022,
		["prio"] = 10,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "PALADIN",
		},
		[30823] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "SHAMAN",
		},
		["Eating/Drinking"] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 90,
		["class"] = "MISC",
		["children"] = {
		["Food"] = true,
		["Drink"] = true,
		["Food & Drink"] = true,
		["Refreshment"] = true,
		},
		["UpdateChildren"] = nil --[[ skipped inline function ]],
		},
		[1786] = {
		["parent"] = 1784,
		["prio"] = 70,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "ROGUE",
		},
		[5599] = {
		["parent"] = 1022,
		["prio"] = 10,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "PALADIN",
		},
		[8457] = {
		["parent"] = 543,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "MAGE",
		},
		[8458] = {
		["parent"] = 543,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "MAGE",
		},
		[10223] = {
		["parent"] = 543,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "MAGE",
		},
		[543] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "MAGE",
		["children"] = {
		[8457] = true,
		[10223] = true,
		[8458] = true,
		[10225] = true,
		},
		["UpdateChildren"] = nil --[[ skipped inline function ]],
		},
		["Drink"] = {
		["parent"] = "Eating/Drinking",
		["prio"] = 90,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "MISC",
		},
		["Food"] = {
		["parent"] = "Eating/Drinking",
		["prio"] = 90,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "MISC",
		},
		[6783] = {
		["parent"] = 5215,
		["prio"] = 70,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "DRUID",
		},
		[498] = {
		["parent"] = 642,
		["prio"] = 10,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "PALADIN",
		},
		[8462] = {
		["parent"] = 6143,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "MAGE",
		},
		[1787] = {
		["parent"] = 1784,
		["prio"] = 70,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "ROGUE",
		},
		[33206] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "PRIEST",
		},
		[31224] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 10,
		["class"] = "ROGUE",
		},
		[9913] = {
		["parent"] = 5215,
		["prio"] = 70,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "DRUID",
		},
		[45182] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 10,
		["class"] = "ROGUE",
		},
		[6940] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "PALADIN",
		["children"] = {
		[20729] = true,
		},
		["UpdateChildren"] = nil --[[ skipped inline function ]],
		},
		[23920] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "WARRIOR",
		},
		[5573] = {
		["parent"] = 642,
		["prio"] = 10,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "PALADIN",
		},
		["Refreshment"] = {
		["parent"] = "Eating/Drinking",
		["prio"] = 90,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "MISC",
		},
		[45438] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 10,
		["class"] = "MAGE",
		},
		[19442] = {
		["parent"] = 7812,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "WARLOCK",
		},
		[19263] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "HUNTER",
		},
		[1020] = {
		["parent"] = 642,
		["prio"] = 10,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "PALADIN",
		},
		[1022] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 10,
		["class"] = "PALADIN",
		["children"] = {
		[10278] = true,
		[5599] = true,
		},
		["UpdateChildren"] = nil --[[ skipped inline function ]],
		},
		[26669] = {
		["parent"] = 5277,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "ROGUE",
		},
		[1784] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 70,
		["class"] = "ROGUE",
		["children"] = {
		[1785] = true,
		[1786] = true,
		[1787] = true,
		},
		["UpdateChildren"] = nil --[[ skipped inline function ]],
		},
		[12975] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "WARRIOR",
		},
		[19443] = {
		["parent"] = 7812,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "WARLOCK",
		},
		[7812] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "WARLOCK",
		["children"] = {
		[19440] = true,
		[19441] = true,
		[19442] = true,
		[19443] = true,
		[19438] = true,
		},
		["UpdateChildren"] = nil --[[ skipped inline function ]],
		},
		["Food & Drink"] = {
		["parent"] = "Eating/Drinking",
		["prio"] = 90,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "MISC",
		},
		[6143] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "MAGE",
		["children"] = {
		[8461] = true,
		[8462] = true,
		[10177] = true,
		[28609] = true,
		},
		["UpdateChildren"] = nil --[[ skipped inline function ]],
		},
		[5277] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "ROGUE",
		["children"] = {
		[26669] = true,
		},
		["UpdateChildren"] = nil --[[ skipped inline function ]],
		},
		[19441] = {
		["parent"] = 7812,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "WARLOCK",
		},
		[3411] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "WARRIOR",
		},
		[871] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "WARRIOR",
		},
		[5215] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 70,
		["class"] = "DRUID",
		["children"] = {
		[6783] = true,
		[9913] = true,
		},
		["UpdateChildren"] = nil --[[ skipped inline function ]],
		},
		[19440] = {
		["parent"] = 7812,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "WARLOCK",
		},
		[10177] = {
		["parent"] = 6143,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "MAGE",
		},
		[20729] = {
		["parent"] = 6940,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "PALADIN",
		},
		[19438] = {
		["parent"] = 7812,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "WARLOCK",
		},
		[11740] = {
		["parent"] = 6229,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "WARLOCK",
		},
		[1785] = {
		["parent"] = 1784,
		["prio"] = 70,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "ROGUE",
		},
		[22812] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "DRUID",
		},
		[28609] = {
		["parent"] = 6143,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "MAGE",
		},
		[28610] = {
		["parent"] = 6229,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "WARLOCK",
		},
		[11739] = {
		["parent"] = 6229,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "WARLOCK",
		},
		[642] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 10,
		["class"] = "PALADIN",
		["children"] = {
		[498] = true,
		[1020] = true,
		[5573] = true,
		},
		["UpdateChildren"] = nil --[[ skipped inline function ]],
		},
		[6229] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 50,
		["class"] = "WARLOCK",
		["children"] = {
		[11739] = true,
		[11740] = true,
		[28610] = true,
		},
		["UpdateChildren"] = nil --[[ skipped inline function ]],
		},
		[19753] = {
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["prio"] = 10,
		["class"] = "PALADIN",
		},
		[8461] = {
		["parent"] = 6143,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "MAGE",
		},
		[10225] = {
		["parent"] = 543,
		["prio"] = 50,
		["state"] = {
		["Bar1"] = {
		["enabled"] = true,
		["glow"] = {
		["enabled"] = false,
		["type"] = "blizz",
		["color"] = {
		1,
		1,
		1,
		1,
		},
		["freq"] = 0.25,
		["border"] = false,
		["customColor"] = false,
		["thickness"] = 1,
		["xOff"] = 0,
		["yOff"] = 0,
		["n"] = 8,
		},
		["ownOnly"] = false,
		},
		},
		["class"] = "MAGE",
		},
		},
		},
		},
	}

    if not SkillCappedBackupDB.BuffOverlayDB then
        SkillCappedBackupDB.BuffOverlayDB = SC:DeepCopy(BuffOverlayDB)
        SkillCappedBackupDB.addonBackupTimes["BuffOverlay"] = SC:GetDateAndTime()
    end

    BuffOverlayDB = scBuffOverlayDB
    SC:UpdateBuffOverlayProfile()
    --SC:UpdateAddonProfileKeysToSkillCapped("BuffOverlayDB")
end

function SC:UpdateBuffOverlayProfile()
    if not BuffOverlayDB then return end
    local playerNameAndRealm = SC:GetPlayerNameAndRealm()
    BuffOverlayDB.profileKeys[playerNameAndRealm] = "SkillCapped"

    for savedPlayerNameAndRealm, _ in pairs(SkillCappedDB.characters) do
        BuffOverlayDB.profileKeys[savedPlayerNameAndRealm] = "SkillCapped"
    end
end