local AddonName, SkillCapped = ...
local SC = SkillCapped

function SC:OmniBarDB()
    local scOmniBarDB = {
        ["namespaces"] = {
        },
        ["profileKeys"] = {
        [SC:GetPlayerNameAndRealm()] = "SkillCapped",
        },
        ["global"] = {
        ["cooldowns"] = {
        [31661] = {
        ["class"] = "MAGE",
        ["duration"] = {
        ["default"] = 32,
        },
        ["name"] = "Dragon's Breath",
        ["icon"] = 134153,
        },
        [853] = {
        ["name"] = "Hammer of Justice",
        ["duration"] = {
        ["default"] = 60,
        [70] = 30,
        },
        ["icon"] = 135963,
        ["class"] = "PALADIN",
        },
        },
        },
        ["profiles"] = {
        ["SkillCapped"] = {
        ["bars"] = {
        ["OmniBar4"] = {
        ["glow"] = true,
        ["scenario"] = false,
        ["tooltips"] = true,
        ["border"] = true,
        ["names"] = false,
        ["multiple"] = true,
        ["showUnused"] = false,
        ["growUpward"] = true,
        ["padding"] = 2,
        ["locked"] = true,
        ["trackUnit"] = "ENEMY",
        ["highlightTarget"] = true,
        ["size"] = 40,
        ["cooldownCount"] = true,
        ["ratedBattleground"] = false,
        ["columns"] = 16,
        ["unusedAlpha"] = 0.45,
        ["align"] = "CENTER",
        ["spells"] = {
        [20066] = true,
        [31661] = true,
        [2094] = true,
        [5211] = true,
        [5246] = true,
        [853] = true,
        [6789] = true,
        [19577] = true,
        [5484] = true,
        [1499] = true,
        [19503] = true,
        [15487] = true,
        [408] = true,
        [8122] = true,
        [19386] = true,
        [30283] = true,
        [12809] = true,
        },
        ["swipeAlpha"] = 0.65,
        ["adaptive"] = false,
        ["maxIcons"] = 32,
        ["world"] = false,
        ["name"] = "Crowd Control",
        ["position"] = {
        ["relativeTo"] = "UIParent",
        ["point"] = "CENTER",
        ["relativePoint"] = "CENTER",
        ["yOfs"] = -131.7408599853516,
        ["xOfs"] = 0,
        ["frameStrata"] = "MEDIUM",
        },
        ["center"] = true,
        ["arena"] = true,
        ["highlightFocus"] = false,
        ["battleground"] = false,
        },
        ["OmniBar5"] = {
        ["glow"] = true,
        ["scenario"] = false,
        ["tooltips"] = true,
        ["border"] = true,
        ["names"] = false,
        ["multiple"] = true,
        ["padding"] = 2,
        ["growUpward"] = true,
        ["showUnused"] = false,
        ["locked"] = true,
        ["swipeAlpha"] = 0.65,
        ["ratedBattleground"] = false,
        ["world"] = false,
        ["cooldownCount"] = true,
        ["highlightTarget"] = true,
        ["columns"] = 8,
        ["unusedAlpha"] = 0.45,
        ["align"] = "LEFT",
        ["spells"] = {
        [586] = true,
        [23920] = true,
        [8177] = true,
        [32379] = true,
        [6940] = false,
        },
        ["trackUnit"] = "ENEMY",
        ["adaptive"] = false,
        ["maxIcons"] = 32,
        ["size"] = 40,
        ["name"] = "Misc",
        ["position"] = {
        ["relativeTo"] = "UIParent",
        ["point"] = "CENTER",
        ["relativePoint"] = "CENTER",
        ["yOfs"] = 176.2301483154297,
        ["xOfs"] = 380,
        ["frameStrata"] = "MEDIUM",
        },
        ["highlightFocus"] = false,
        ["arena"] = true,
        ["center"] = false,
        ["battleground"] = false,
        },
        ["OmniBar1"] = {
        ["glow"] = true,
        ["scenario"] = false,
        ["border"] = true,
        ["tooltips"] = true,
        ["names"] = false,
        ["multiple"] = true,
        ["padding"] = 2,
        ["highlightFocus"] = false,
        ["showUnused"] = false,
        ["swipeAlpha"] = 0.65,
        ["trackUnit"] = "ENEMY",
        ["ratedBattleground"] = false,
        ["world"] = false,
        ["cooldownCount"] = true,
        ["highlightTarget"] = true,
        ["columns"] = 8,
        ["unusedAlpha"] = 0.45,
        ["align"] = "CENTER",
        ["spells"] = {
        [2139] = true,
        [586] = false,
        [32379] = false,
        [31935] = true,
        [1766] = true,
        [23920] = false,
        [6552] = true,
        [19244] = true,
        [16979] = true,
        [34490] = true,
        [8042] = true,
        },
        ["locked"] = true,
        ["adaptive"] = false,
        ["maxIcons"] = 32,
        ["size"] = 45,
        ["name"] = "Interrupts",
        ["position"] = {
        ["relativeTo"] = "UIParent",
        ["point"] = "CENTER",
        ["relativePoint"] = "CENTER",
        ["yOfs"] = -218.9886016845703,
        ["xOfs"] = 0,
        ["frameStrata"] = "MEDIUM",
        },
        ["growUpward"] = true,
        ["arena"] = true,
        ["center"] = true,
        ["battleground"] = false,
        },
        ["OmniBar2"] = {
        ["glow"] = true,
        ["scenario"] = false,
        ["tooltips"] = true,
        ["border"] = true,
        ["names"] = false,
        ["multiple"] = true,
        ["showUnused"] = false,
        ["highlightFocus"] = false,
        ["padding"] = 2,
        ["swipeAlpha"] = 0.65,
        ["locked"] = true,
        ["highlightTarget"] = true,
        ["size"] = 40,
        ["cooldownCount"] = true,
        ["ratedBattleground"] = false,
        ["columns"] = 16,
        ["unusedAlpha"] = 0.45,
        ["align"] = "CENTER",
        ["spells"] = {
        [14185] = true,
        [586] = false,
        [724] = true,
        [2651] = true,
        [13908] = true,
        [6940] = true,
        [19752] = true,
        [11958] = true,
        [22842] = true,
        [2983] = false,
        [31224] = true,
        [2944] = true,
        [11426] = false,
        [23920] = false,
        [5384] = false,
        [19263] = true,
        [642] = true,
        [1022] = true,
        [16188] = true,
        [16190] = true,
        [5277] = true,
        [33206] = true,
        [3411] = true,
        [12975] = true,
        [498] = false,
        [17116] = true,
        [32379] = false,
        [2139] = false,
        [22812] = true,
        [1856] = true,
        [13896] = false,
        [871] = true,
        [20230] = true,
        [45438] = true,
        [740] = true,
        [30823] = true,
        [36554] = false,
        [18708] = true,
        [633] = true,
        [23989] = true,
        },
        ["trackUnit"] = "ENEMY",
        ["adaptive"] = false,
        ["maxIcons"] = 32,
        ["world"] = false,
        ["name"] = "Defensives",
        ["position"] = {
        ["relativeTo"] = "UIParent",
        ["point"] = "CENTER",
        ["relativePoint"] = "CENTER",
        ["yOfs"] = -173.9799041748047,
        ["xOfs"] = 0,
        ["frameStrata"] = "MEDIUM",
        },
        ["center"] = true,
        ["arena"] = true,
        ["growUpward"] = true,
        ["battleground"] = false,
        },
        },
        },
        },
    }

    if not SkillCappedBackupDB.OmniBarDB then
        SkillCappedBackupDB.OmniBarDB = SC:DeepCopy(OmniBarDB)
        SkillCappedBackupDB.addonBackupTimes["OmniBar"] = SC:GetDateAndTime()
    end

    OmniBarDB = scOmniBarDB

    SC:UpdateOmniBarProfile()
end

function SC:UpdateOmniBarProfile()
    if not OmniBarDB then return end
    if not SkillCappedBackupDB.OmniBarDB then return end
    local playerNameAndRealm = SC:GetPlayerNameAndRealm()
    OmniBarDB.profileKeys[playerNameAndRealm] = "SkillCapped"

    for savedPlayerNameAndRealm, _ in pairs(SkillCappedDB.characters) do
        OmniBarDB.profileKeys[savedPlayerNameAndRealm] = "SkillCapped"
    end
end